package eu.kanade.tachiyomi.animeextension.all.missav

import eu.kanade.tachiyomi.animesource.model.AnimeFilter
import eu.kanade.tachiyomi.animesource.model.AnimeFilterList

abstract class SelectFilter(
    name: String,
    private val options: List<Pair<String, String>>,
) : AnimeFilter.Select<String>(
    name,
    options.map { it.first }.toTypedArray(),
) {
    val selected get() = options[state].second.takeUnless { state == 0 }
}

class SortFilter :
    SelectFilter(
        "Sort by",
        SORT,
    ) {
    companion object {
        val SORT = listOf(
            Pair("Release date", "released_at"),
            Pair("Recent update", "published_at"),
            Pair("Today views", "today_views"),
            Pair("Weekly views", "weekly_views"),
            Pair("Monthly views", "monthly_views"),
            Pair("Total views", "views"),
        )
    }
}

class GenreList :
    SelectFilter(
        "Genres",
        GENRES,
    ) {
    companion object {
        val GENRES = listOf(
            Pair("<Select>", ""),
            Pair("16 Hours Or More", "en/genres/16%20Hours%20Or%20More"),
            Pair("30 Years Old", "en/genres/30%20Years%20Old"),
            Pair("3D", "en/genres/3D"),
            Pair("3P", "en/genres/3P"),
            Pair("3P / 4P", "en/genres/3P%20/%204P"),
            Pair("3P, 4P", "en/genres/3P,%204P"),
            Pair("4 Hours Or More", "en/genres/4%20Hours%20Or%20More"),
            Pair("4 Hours Past Work Time", "en/genres/4%20Hours%20Past%20Work%20Time"),
            Pair("40 Years Old", "en/genres/40%20Years%20Old"),
            Pair("4K", "en/genres/4K"),
            Pair("50 Minutes", "en/genres/50%20Minutes"),
            Pair("50 Years Old", "en/genres/50%20Years%20Old"),
            Pair("69", "en/genres/69"),
            Pair("8Kvr", "en/genres/8Kvr"),
            Pair("Acme Orgasm", "en/genres/Acme%20Orgasm"),
            Pair("Acting", "en/genres/Acting"),
            Pair("Actress", "en/genres/Actress"),
            Pair("Actress Collection", "en/genres/Actress%20Collection"),
            Pair("Addition", "en/genres/Addition"),
            Pair("Administration", "en/genres/Administration"),
            Pair("Administrator Recommended Works", "en/genres/Administrator%20Recommended%20Works"),
            Pair("Adopted Daughter", "en/genres/Adopted%20Daughter"),
            Pair("Adult Movie", "en/genres/Adult%20Movie"),
            Pair("Adultery", "en/genres/Adultery"),
            Pair("Advanced", "en/genres/Advanced"),
            Pair("Adventure", "en/genres/Adventure"),
            Pair("Advertising Idol", "en/genres/Advertising%20Idol"),
            Pair("Advertising Male Idol", "en/genres/Advertising%20Male%20Idol"),
            Pair("Aesthetics And Massage", "en/genres/Aesthetics%20And%20Massage"),
            Pair("Age-Old Wife", "en/genres/Age-Old%20Wife"),
            Pair("Ai-Generated Works", "en/genres/Ai-Generated%20Works"),
            Pair("Amateur", "en/genres/Amateur"),
            Pair("Anal", "en/genres/Anal"),
            Pair("Anal Sex", "en/genres/Anal%20Sex"),
            Pair("Anal Sex (Cross-Dressing Man)", "en/genres/Anal%20Sex%20%28Cross-Dressing%20Man%29"),
            Pair("Anchorwoman", "en/genres/Anchorwoman"),
            Pair("Animation", "en/genres/Animation"),
            Pair("Anime Character", "en/genres/Anime%20Character"),
            Pair("Anus", "en/genres/Anus"),
            Pair("Aokan", "en/genres/Aokan"),
            Pair("Aphrodisiac", "en/genres/Aphrodisiac"),
            Pair("Apron", "en/genres/Apron"),
            Pair("Artist", "en/genres/Artist"),
            Pair("Asian Actress", "en/genres/Asian%20Actress"),
            Pair("Ass", "en/genres/Ass"),
            Pair("Athlete", "en/genres/Athlete"),
            Pair("Atmosphere", "en/genres/Atmosphere"),
            Pair("Aunt", "en/genres/Aunt"),
            Pair("Av Open 2014 Heavyweight", "en/genres/Av%20Open%202014%20Heavyweight"),
            Pair("Av Open 2014 Middleweight", "en/genres/Av%20Open%202014%20Middleweight"),
            Pair("Av Open 2014 Super Heavyweight", "en/genres/Av%20Open%202014%20Super%20Heavyweight"),
            Pair("Av Open 2015 Actress Department", "en/genres/Av%20Open%202015%20Actress%20Department"),
            Pair("Av Open 2015 Fetish Department", "en/genres/Av%20Open%202015%20Fetish%20Department"),
            Pair("Av Open 2015 Girls Department", "en/genres/Av%20Open%202015%20Girls%20Department"),
            Pair("Av Open 2015 Mature Woman Department", "en/genres/Av%20Open%202015%20Mature%20Woman%20Department"),
            Pair("Av Open 2015 Ordinary Department", "en/genres/Av%20Open%202015%20Ordinary%20Department"),
            Pair("Av Open 2015 Planning Department", "en/genres/Av%20Open%202015%20Planning%20Department"),
            Pair("Av Open 2015 Sm Department", "en/genres/Av%20Open%202015%20Sm%20Department"),
            Pair("Av Open 2016 Actress Department", "en/genres/Av%20Open%202016%20Actress%20Department"),
            Pair("Av Open 2016 Drama Department", "en/genres/Av%20Open%202016%20Drama%20Department"),
            Pair("Av Open 2016 Fetish Department", "en/genres/Av%20Open%202016%20Fetish%20Department"),
            Pair("Av Open 2016 Girls Department", "en/genres/Av%20Open%202016%20Girls%20Department"),
            Pair("Av Open 2016 Hardcore Department", "en/genres/Av%20Open%202016%20Hardcore%20Department"),
            Pair("Av Open 2016 Mature Woman Department", "en/genres/Av%20Open%202016%20Mature%20Woman%20Department"),
            Pair("Av Open 2016 Ordinary Department", "en/genres/Av%20Open%202016%20Ordinary%20Department"),
            Pair("Av Open 2016 Planning Department", "en/genres/Av%20Open%202016%20Planning%20Department"),
            Pair("Av Open 2016 Variety Show Department", "en/genres/Av%20Open%202016%20Variety%20Show%20Department"),
            Pair("Av Open 2017 Actress Department", "en/genres/Av%20Open%202017%20Actress%20Department"),
            Pair("Av Open 2017 Documentary Department", "en/genres/Av%20Open%202017%20Documentary%20Department"),
            Pair("Av Open 2017 Drama Department", "en/genres/Av%20Open%202017%20Drama%20Department"),
            Pair("Av Open 2017 Fetish Department", "en/genres/Av%20Open%202017%20Fetish%20Department"),
            Pair("Av Open 2017 Girls Department", "en/genres/Av%20Open%202017%20Girls%20Department"),
            Pair("Av Open 2017 Hardcore Department", "en/genres/Av%20Open%202017%20Hardcore%20Department"),
            Pair("Av Open 2017 Mania Department", "en/genres/Av%20Open%202017%20Mania%20Department"),
            Pair("Av Open 2017 Mature Woman Department", "en/genres/Av%20Open%202017%20Mature%20Woman%20Department"),
            Pair("Av Open 2017 Ordinary Department", "en/genres/Av%20Open%202017%20Ordinary%20Department"),
            Pair("Av Open 2017 Planning Department", "en/genres/Av%20Open%202017%20Planning%20Department"),
            Pair("Av Open 2018 Fetish Department", "en/genres/Av%20Open%202018%20Fetish%20Department"),
            Pair("Av Open 2018 Girls Department", "en/genres/Av%20Open%202018%20Girls%20Department"),
            Pair("Av Open 2018 Hardcore Department", "en/genres/Av%20Open%202018%20Hardcore%20Department"),
            Pair("Av Open 2018 Mature Woman Department", "en/genres/Av%20Open%202018%20Mature%20Woman%20Department"),
            Pair("Av Open 2018 Ordinary Department", "en/genres/Av%20Open%202018%20Ordinary%20Department"),
            Pair("Av Open 2018 Planning Department", "en/genres/Av%20Open%202018%20Planning%20Department"),
            Pair("Baby Face", "en/genres/Baby%20Face"),
            Pair("Back", "en/genres/Back"),
            Pair("Ball Gag", "en/genres/Ball%20Gag"),
            Pair("Bareback", "en/genres/Bareback"),
            Pair("Baseball Fist", "en/genres/Baseball%20Fist"),
            Pair("Bathing", "en/genres/Bathing"),
            Pair("Bathtub", "en/genres/Bathtub"),
            Pair("Beautiful Breasts", "en/genres/Beautiful%20Breasts"),
            Pair("Beautiful Butt", "en/genres/Beautiful%20Butt"),
            Pair("Beautiful Cat", "en/genres/Beautiful%20Cat"),
            Pair("Beautiful Chest", "en/genres/Beautiful%20Chest"),
            Pair("Beautiful Girl", "en/genres/Beautiful%20Girl"),
            Pair("Beautiful Legs", "en/genres/Beautiful%20Legs"),
            Pair("Beautiful Mature Woman", "en/genres/Beautiful%20Mature%20Woman"),
            Pair("Beautiful Skin / Whitening", "en/genres/Beautiful%20Skin%20/%20Whitening"),
            Pair("Beautiful Skin And Whitening", "en/genres/Beautiful%20Skin%20And%20Whitening"),
            Pair("Beautiful Woman", "en/genres/Beautiful%20Woman"),
            Pair("Beauty Salon And Massage", "en/genres/Beauty%20Salon%20And%20Massage"),
            Pair("Being Cheated On / Acts Of Being Cheated On", "en/genres/Being%20Cheated%20On%20/%20Acts%20Of%20Being%20Cheated%20On"),
            Pair("Best", "en/genres/Best"),
            Pair("Best / Complete", "en/genres/Best%20/%20Complete"),
            Pair("Best Of All", "en/genres/Best%20Of%20All"),
            Pair("Best, Omnibus", "en/genres/Best,%20Omnibus"),
            Pair("Big Ass", "en/genres/Big%20Ass"),
            Pair("Big Breast Fetish", "en/genres/Big%20Breast%20Fetish"),
            Pair("Big Breasts", "en/genres/Big%20Breasts"),
            Pair("Big Butt", "en/genres/Big%20Butt"),
            Pair("Big Chicken", "en/genres/Big%20Chicken"),
            Pair("Big Cock", "en/genres/Big%20Cock"),
            Pair("Big Pennis", "en/genres/Big%20Pennis"),
            Pair("Bikini", "en/genres/Bikini"),
            Pair("Bishri", "en/genres/Bishri"),
            Pair("Bitch", "en/genres/Bitch"),
            Pair("Bl", "en/genres/Bl"),
            Pair("Black Hair", "en/genres/Black%20Hair"),
            Pair("Black Male Actor", "en/genres/Black%20Male%20Actor"),
            Pair("Bleached Spots", "en/genres/Bleached%20Spots"),
            Pair("Blond", "en/genres/Blond"),
            Pair("Blonde", "en/genres/Blonde"),
            Pair("Blonde / Blonde", "en/genres/Blonde%20/%20Blonde"),
            Pair("Bloomers", "en/genres/Bloomers"),
            Pair("Blow Mono", "en/genres/Blow%20Mono"),
            Pair("Blowjob", "en/genres/Blowjob"),
            Pair("Body Piercing", "en/genres/Body%20Piercing"),
            Pair("Bonus Footage Exclusive To Mgs Included", "en/genres/Bonus%20Footage%20Exclusive%20To%20Mgs%20Included"),
            Pair("Bonus Images Included", "en/genres/Bonus%20Images%20Included"),
            Pair("Boots", "en/genres/Boots"),
            Pair("Braless", "en/genres/Braless"),
            Pair("Breast Milk", "en/genres/Breast%20Milk"),
            Pair("Bride", "en/genres/Bride"),
            Pair("Bride / Young Wife", "en/genres/Bride%20/%20Young%20Wife"),
            Pair("Bronze", "en/genres/Bronze"),
            Pair("Brown Hair", "en/genres/Brown%20Hair"),
            Pair("Brush Down", "en/genres/Brush%20Down"),
            Pair("Bubble Bath", "en/genres/Bubble%20Bath"),
            Pair("Bubble Socks", "en/genres/Bubble%20Socks"),
            Pair("Bukkake", "en/genres/Bukkake"),
            Pair("Bunny Girl", "en/genres/Bunny%20Girl"),
            Pair("Business Clothing", "en/genres/Business%20Clothing"),
            Pair("Butt", "en/genres/Butt"),
            Pair("Butt Fetish", "en/genres/Butt%20Fetish"),
            Pair("By Idol", "en/genres/By%20Idol"),
            Pair("Call Girl", "en/genres/Call%20Girl"),
            Pair("Camouflage, Masculine Woman", "en/genres/Camouflage,%20Masculine%20Woman"),
            Pair("Campus Story", "en/genres/Campus%20Story"),
            Pair("Candle", "en/genres/Candle"),
            Pair("Car Love", "en/genres/Car%20Love"),
            Pair("Car Sex", "en/genres/Car%20Sex"),
            Pair("Catwoman", "en/genres/Catwoman"),
            Pair("Celebrity", "en/genres/Celebrity"),
            Pair("Chaos", "en/genres/Chaos"),
            Pair("Cheating", "en/genres/Cheating"),
            Pair("Cheating / Cuckold", "en/genres/Cheating%20/%20Cuckold"),
            Pair("Cheating Wife / Ntr / Cuckold", "en/genres/Cheating%20Wife%20/%20Ntr%20/%20Cuckold"),
            Pair("Cheating Wife, Ntr, Cuckold", "en/genres/Cheating%20Wife,%20Ntr,%20Cuckold"),
            Pair("Cheerleaders", "en/genres/Cheerleaders"),
            Pair("Cheongsam", "en/genres/Cheongsam"),
            Pair("Chest", "en/genres/Chest"),
            Pair("Chief", "en/genres/Chief"),
            Pair("Chijo", "en/genres/Chijo"),
            Pair("Childhood", "en/genres/Childhood"),
            Pair("Childish Face", "en/genres/Childish%20Face"),
            Pair("Classic", "en/genres/Classic"),
            Pair("Cleaning Blowjob", "en/genres/Cleaning%20Blowjob"),
            Pair("Clinic", "en/genres/Clinic"),
            Pair("Clinic / Laboratory", "en/genres/Clinic%20/%20Laboratory"),
            Pair("Close Up", "en/genres/Close%20Up"),
            Pair("Clothes", "en/genres/Clothes"),
            Pair("Club Activity Manager", "en/genres/Club%20Activity%20Manager"),
            Pair("Collaborative Work", "en/genres/Collaborative%20Work"),
            Pair("Collection", "en/genres/Collection"),
            Pair("Coma", "en/genres/Coma"),
            Pair("Comes With Bonus Footage Only Available At Mgs", "en/genres/Comes%20With%20Bonus%20Footage%20Only%20Available%20At%20Mgs"),
            Pair("Comes With Bonus Footage Only For Mgs", "en/genres/Comes%20With%20Bonus%20Footage%20Only%20For%20Mgs"),
            Pair("Common Sense", "en/genres/Common%20Sense"),
            Pair("Confession Experience", "en/genres/Confession%20Experience"),
            Pair("Confinement", "en/genres/Confinement"),
            Pair("Consecutive Coat", "en/genres/Consecutive%20Coat"),
            Pair("Contribution", "en/genres/Contribution"),
            Pair("Cosplay", "en/genres/Cosplay"),
            Pair("Couple", "en/genres/Couple"),
            Pair("Cow Calf", "en/genres/Cow%20Calf"),
            Pair("Cowgirl", "en/genres/Cowgirl"),
            Pair("Creampie", "en/genres/Creampie"),
            Pair("Cruel", "en/genres/Cruel"),
            Pair("Cuckold", "en/genres/Cuckold"),
            Pair("Cuckolding / Being Cuckolded", "en/genres/Cuckolding%20/%20Being%20Cuckolded"),
            Pair("Cum In Mouth", "en/genres/Cum%20In%20Mouth"),
            Pair("Cunnilingus", "en/genres/Cunnilingus"),
            Pair("Curls", "en/genres/Curls"),
            Pair("Customs", "en/genres/Customs"),
            Pair("Cute Little Boy", "en/genres/Cute%20Little%20Boy"),
            Pair("D Cup", "en/genres/D%20Cup"),
            Pair("Daihatsu Hat / Ntr", "en/genres/Daihatsu%20Hat%20/%20Ntr"),
            Pair("Dance", "en/genres/Dance"),
            Pair("Dark Style", "en/genres/Dark%20Style"),
            Pair("Dark System", "en/genres/Dark%20System"),
            Pair("Dating", "en/genres/Dating"),
            Pair("De M", "en/genres/De%20M"),
            Pair("Debut", "en/genres/Debut"),
            Pair("Decatin", "en/genres/Decatin"),
            Pair("Dedo Work", "en/genres/Dedo%20Work"),
            Pair("Deep Throat", "en/genres/Deep%20Throat"),
            Pair("Defecation", "en/genres/Defecation"),
            Pair("Delivery Only", "en/genres/Delivery%20Only"),
            Pair("Delivery-Only Amateur", "en/genres/Delivery-Only%20Amateur"),
            Pair("Delusion", "en/genres/Delusion"),
            Pair("Deriheru", "en/genres/Deriheru"),
            Pair("Devil", "en/genres/Devil"),
            Pair("Dildo", "en/genres/Dildo"),
            Pair("Dirty Talk", "en/genres/Dirty%20Talk"),
            Pair("Dirty Words", "en/genres/Dirty%20Words"),
            Pair("Distribution Only", "en/genres/Distribution%20Only"),
            Pair("Dmm Distribution Co., Ltd.", "en/genres/Dmm%20Distribution%20Co.,%20Ltd."),
            Pair("Documentary", "en/genres/Documentary"),
            Pair("Doggy Style", "en/genres/Doggy%20Style"),
            Pair("Doll", "en/genres/Doll"),
            Pair("Double Penetration", "en/genres/Double%20Penetration"),
            Pair("Drink Saliva", "en/genres/Drink%20Saliva"),
            Pair("Drink Urine", "en/genres/Drink%20Urine"),
            Pair("Drugs And Aphrodisiacs", "en/genres/Drugs%20And%20Aphrodisiacs"),
            Pair("Drunk", "en/genres/Drunk"),
            Pair("E Cup", "en/genres/E%20Cup"),
            Pair("Eat Pussy", "en/genres/Eat%20Pussy"),
            Pair("Eat Shit", "en/genres/Eat%20Shit"),
            Pair("Ejection", "en/genres/Ejection"),
            Pair("Elder Sister", "en/genres/Elder%20Sister"),
            Pair("Electric Machine", "en/genres/Electric%20Machine"),
            Pair("Emmanuel", "en/genres/Emmanuel"),
            Pair("Emulsion Oil", "en/genres/Emulsion%20Oil"),
            Pair("Enema", "en/genres/Enema"),
            Pair("Entertainer", "en/genres/Entertainer"),
            Pair("Erotic", "en/genres/Erotic"),
            Pair("Erotic Photo", "en/genres/Erotic%20Photo"),
            Pair("Esthetic Massage", "en/genres/Esthetic%20Massage"),
            Pair("Exactly Like", "en/genres/Exactly%20Like"),
            Pair("Exclusive", "en/genres/Exclusive"),
            Pair("Exhibition", "en/genres/Exhibition"),
            Pair("Expensive", "en/genres/Expensive"),
            Pair("Experimental Plain White", "en/genres/Experimental%20Plain%20White"),
            Pair("Expose", "en/genres/Expose"),
            Pair("Exposure", "en/genres/Exposure"),
            Pair("Extreme Orgasm", "en/genres/Extreme%20Orgasm"),
            Pair("Extreme Storm Surge", "en/genres/Extreme%20Storm%20Surge"),
            Pair("F Cup", "en/genres/F%20Cup"),
            Pair("Face Ride", "en/genres/Face%20Ride"),
            Pair("Face Shot", "en/genres/Face%20Shot"),
            Pair("Faction", "en/genres/Faction"),
            Pair("Fair Skin", "en/genres/Fair%20Skin"),
            Pair("Fantasy", "en/genres/Fantasy"),
            Pair("Fanza Limited", "en/genres/Fanza%20Limited"),
            Pair("Farting Love", "en/genres/Farting%20Love"),
            Pair("Fat Girl", "en/genres/Fat%20Girl"),
            Pair("Fear", "en/genres/Fear"),
            Pair("Female Boss", "en/genres/Female%20Boss"),
            Pair("Female College Student", "en/genres/Female%20College%20Student"),
            Pair("Female Doctor", "en/genres/Female%20Doctor"),
            Pair("Female Investigator", "en/genres/Female%20Investigator"),
            Pair("Female Main Angle", "en/genres/Female%20Main%20Angle"),
            Pair("Female Ninja", "en/genres/Female%20Ninja"),
            Pair("Female Teacher", "en/genres/Female%20Teacher"),
            Pair("Female Warrior", "en/genres/Female%20Warrior"),
            Pair("Femdom Slave", "en/genres/Femdom%20Slave"),
            Pair("Feminine", "en/genres/Feminine"),
            Pair("Fetish", "en/genres/Fetish"),
            Pair("Fifty", "en/genres/Fifty"),
            Pair("Fighter", "en/genres/Fighter"),
            Pair("Fighting", "en/genres/Fighting"),
            Pair("Fingering", "en/genres/Fingering"),
            Pair("First Shoot", "en/genres/First%20Shoot"),
            Pair("First Shot", "en/genres/First%20Shot"),
            Pair("First Time Filming", "en/genres/First%20Time%20Filming"),
            Pair("Fist", "en/genres/Fist"),
            Pair("Flight Attendant", "en/genres/Flight%20Attendant"),
            Pair("Foot Fetish", "en/genres/Foot%20Fetish"),
            Pair("Footjob", "en/genres/Footjob"),
            Pair("Forced Blowjob", "en/genres/Forced%20Blowjob"),
            Pair("Foreign Actress", "en/genres/Foreign%20Actress"),
            Pair("Foreign Object Penetration", "en/genres/Foreign%20Object%20Penetration"),
            Pair("Foreigner", "en/genres/Foreigner"),
            Pair("Forties", "en/genres/Forties"),
            Pair("Forty Years Old", "en/genres/Forty%20Years%20Old"),
            Pair("Freeter", "en/genres/Freeter"),
            Pair("Frenzy", "en/genres/Frenzy"),
            Pair("Friend", "en/genres/Friend"),
            Pair("Full Hd (Fhd)", "en/genres/Full%20Hd%20%28Fhd%29"),
            Pair("G Cup", "en/genres/G%20Cup"),
            Pair("Gang Rape", "en/genres/Gang%20Rape"),
            Pair("Gangster", "en/genres/Gangster"),
            Pair("Gansha", "en/genres/Gansha"),
            Pair("Gay Homo", "en/genres/Gay%20Homo"),
            Pair("Geek", "en/genres/Geek"),
            Pair("Girl Guide", "en/genres/Girl%20Guide"),
            Pair("Glasses Girl", "en/genres/Glasses%20Girl"),
            Pair("God Of Sex", "en/genres/God%20Of%20Sex"),
            Pair("Grandfather", "en/genres/Grandfather"),
            Pair("Grandma", "en/genres/Grandma"),
            Pair("Group Bukkake", "en/genres/Group%20Bukkake"),
            Pair("Gym Suit", "en/genres/Gym%20Suit"),
            Pair("H Cup", "en/genres/H%20Cup"),
            Pair("Hair Salons And Massage Parlors", "en/genres/Hair%20Salons%20And%20Massage%20Parlors"),
            Pair("Hairlessness", "en/genres/Hairlessness"),
            Pair("Hairy", "en/genres/Hairy"),
            Pair("Half", "en/genres/Half"),
            Pair("Handjob", "en/genres/Handjob"),
            Pair("Handjob And Blowjob", "en/genres/Handjob%20And%20Blowjob"),
            Pair("Hardcore", "en/genres/Hardcore"),
            Pair("Harem", "en/genres/Harem"),
            Pair("Hatsuura", "en/genres/Hatsuura"),
            Pair("Hd", "en/genres/Hd"),
            Pair("Health Care", "en/genres/Health%20Care"),
            Pair("Heaven Tv", "en/genres/Heaven%20Tv"),
            Pair("Hell Road", "en/genres/Hell%20Road"),
            Pair("High Definition", "en/genres/High%20Definition"),
            Pair("High Definition (Hd)", "en/genres/High%20Definition%20%28Hd%29"),
            Pair("High Heels", "en/genres/High%20Heels"),
            Pair("High Quality Vr", "en/genres/High%20Quality%20Vr"),
            Pair("High School Girl", "en/genres/High%20School%20Girl"),
            Pair("Historical Drama", "en/genres/Historical%20Drama"),
            Pair("Hit On Boys", "en/genres/Hit%20On%20Boys"),
            Pair("Hit On Girls", "en/genres/Hit%20On%20Girls"),
            Pair("Homosexual", "en/genres/Homosexual"),
            Pair("Horror", "en/genres/Horror"),
            Pair("Horse Riding", "en/genres/Horse%20Riding"),
            Pair("Hospital", "en/genres/Hospital"),
            Pair("Hospitals And Clinics", "en/genres/Hospitals%20And%20Clinics"),
            Pair("Hostess", "en/genres/Hostess"),
            Pair("Hot Girl", "en/genres/Hot%20Girl"),
            Pair("Hot Spring", "en/genres/Hot%20Spring"),
            Pair("Hot Water", "en/genres/Hot%20Water"),
            Pair("Hotehel", "en/genres/Hotehel"),
            Pair("Hotel", "en/genres/Hotel"),
            Pair("Hotel Owner", "en/genres/Hotel%20Owner"),
            Pair("Housewife", "en/genres/Housewife"),
            Pair("How To", "en/genres/How%20To"),
            Pair("Human Monster", "en/genres/Human%20Monster"),
            Pair("Humiliation", "en/genres/Humiliation"),
            Pair("Husband And Wife", "en/genres/Husband%20And%20Wife"),
            Pair("Hypnosis", "en/genres/Hypnosis"),
            Pair("Hypnotic Brainwashing", "en/genres/Hypnotic%20Brainwashing"),
            Pair("Hysteroscope", "en/genres/Hysteroscope"),
            Pair("I Cup", "en/genres/I%20Cup"),
            Pair("Idol", "en/genres/Idol"),
            Pair("Ignoring", "en/genres/Ignoring"),
            Pair("Immediate Saddle", "en/genres/Immediate%20Saddle"),
            Pair("Imprisonment", "en/genres/Imprisonment"),
            Pair("In Love", "en/genres/In%20Love"),
            Pair("Incest", "en/genres/Incest"),
            Pair("Incident", "en/genres/Incident"),
            Pair("Indie", "en/genres/Indie"),
            Pair("Individual", "en/genres/Individual"),
            Pair("Ingo", "en/genres/Ingo"),
            Pair("Instant Sex", "en/genres/Instant%20Sex"),
            Pair("Insult", "en/genres/Insult"),
            Pair("Intercourse", "en/genres/Intercourse"),
            Pair("Internal Ejaculation", "en/genres/Internal%20Ejaculation"),
            Pair("Interview", "en/genres/Interview"),
            Pair("Its Pretty Clean", "en/genres/Its%20Pretty%20Clean"),
            Pair("J Cup", "en/genres/J%20Cup"),
            Pair("Judai (Teen) With E Cup Or More", "en/genres/Judai%20%28Teen%29%20With%20E%20Cup%20Or%20More"),
            Pair("Junko", "en/genres/Junko"),
            Pair("Kakuiro Role", "en/genres/Kakuiro%20Role"),
            Pair("Kimono", "en/genres/Kimono"),
            Pair("Kimono / Yukata", "en/genres/Kimono%20/%20Yukata"),
            Pair("Kimono And Yukata", "en/genres/Kimono%20And%20Yukata"),
            Pair("Kireina_Onesan", "en/genres/Kireina_Onesan"),
            Pair("Kiss", "en/genres/Kiss"),
            Pair("Kiss Of Same-Sex Love", "en/genres/Kiss%20Of%20Same-Sex%20Love"),
            Pair("Knee Socks", "en/genres/Knee%20Socks"),
            Pair("Kogal", "en/genres/Kogal"),
            Pair("Kounai Hassha", "en/genres/Kounai%20Hassha"),
            Pair("Kyoshi", "en/genres/Kyoshi"),
            Pair("Labyrinth / Small", "en/genres/Labyrinth%20/%20Small"),
            Pair("Lady", "en/genres/Lady"),
            Pair("Large Breasts", "en/genres/Large%20Breasts"),
            Pair("Lecturer", "en/genres/Lecturer"),
            Pair("Leg Crossing", "en/genres/Leg%20Crossing"),
            Pair("Lesbian", "en/genres/Lesbian"),
            Pair("Lesbian Kiss", "en/genres/Lesbian%20Kiss"),
            Pair("Lets Go", "en/genres/Lets%20Go"),
            Pair("Lewd Nasty Lady", "en/genres/Lewd%20Nasty%20Lady"),
            Pair("Limited Time", "en/genres/Limited%20Time"),
            Pair("Limited Time Sale", "en/genres/Limited%20Time%20Sale"),
            Pair("Limited To Dmm Distribution", "en/genres/Limited%20To%20Dmm%20Distribution"),
            Pair("Limitless Reality", "en/genres/Limitless%20Reality"),
            Pair("Liquor Store", "en/genres/Liquor%20Store"),
            Pair("Lolita", "en/genres/Lolita"),
            Pair("Long", "en/genres/Long"),
            Pair("Long Hair", "en/genres/Long%20Hair"),
            Pair("Lotion", "en/genres/Lotion"),
            Pair("Love", "en/genres/Love"),
            Pair("Love Affair", "en/genres/Love%20Affair"),
            Pair("Love And Sex", "en/genres/Love%20And%20Sex"),
            Pair("Low Cost Movies", "en/genres/Low%20Cost%20Movies"),
            Pair("Lucky Bag", "en/genres/Lucky%20Bag"),
            Pair("M Female", "en/genres/M%20Female"),
            Pair("M Leg", "en/genres/M%20Leg"),
            Pair("M Male", "en/genres/M%20Male"),
            Pair("M Woman", "en/genres/M%20Woman"),
            Pair("M_Yes", "en/genres/M_Yes"),
            Pair("Magical Girl", "en/genres/Magical%20Girl"),
            Pair("Maid", "en/genres/Maid"),
            Pair("Male And Female Sex", "en/genres/Male%20And%20Female%20Sex"),
            Pair("Male Squirting", "en/genres/Male%20Squirting"),
            Pair("Maltreat", "en/genres/Maltreat"),
            Pair("Manners And Customs", "en/genres/Manners%20And%20Customs"),
            Pair("Many Stories", "en/genres/Many%20Stories"),
            Pair("Married Woman", "en/genres/Married%20Woman"),
            Pair("Marrying For Business", "en/genres/Marrying%20For%20Business"),
            Pair("Mask", "en/genres/Mask"),
            Pair("Massage", "en/genres/Massage"),
            Pair("Massage / Tea Tea Ceremony", "en/genres/Massage%20/%20Tea%20Tea%20Ceremony"),
            Pair("Massage Oil", "en/genres/Massage%20Oil"),
            Pair("Masturbate", "en/genres/Masturbate"),
            Pair("Masturbation", "en/genres/Masturbation"),
            Pair("Masturbation Support", "en/genres/Masturbation%20Support"),
            Pair("Masumi", "en/genres/Masumi"),
            Pair("Mature Beauty", "en/genres/Mature%20Beauty"),
            Pair("Mature Woman", "en/genres/Mature%20Woman"),
            Pair("Mature Woman / Married Woman", "en/genres/Mature%20Woman%20/%20Married%20Woman"),
            Pair("Mature Women / Married Women", "en/genres/Mature%20Women%20/%20Married%20Women"),
            Pair("Medical Examination", "en/genres/Medical%20Examination"),
            Pair("Medium Hair", "en/genres/Medium%20Hair"),
            Pair("Meeting", "en/genres/Meeting"),
            Pair("Men And Women", "en/genres/Men%20And%20Women"),
            Pair("Micro", "en/genres/Micro"),
            Pair("Minamibuchi", "en/genres/Minamibuchi"),
            Pair("Mini", "en/genres/Mini"),
            Pair("Mini / Petit", "en/genres/Mini%20/%20Petit"),
            Pair("Mini Skirt", "en/genres/Mini%20Skirt"),
            Pair("Mini Small", "en/genres/Mini%20Small"),
            Pair("Miniskirt Policewoman", "en/genres/Miniskirt%20Policewoman"),
            Pair("Miscaba", "en/genres/Miscaba"),
            Pair("Mischief", "en/genres/Mischief"),
            Pair("Missy", "en/genres/Missy"),
            Pair("Mistress Japanese Geisha", "en/genres/Mistress%20Japanese%20Geisha"),
            Pair("Mizute Clothes", "en/genres/Mizute%20Clothes"),
            Pair("Model", "en/genres/Model"),
            Pair("Model System", "en/genres/Model%20System"),
            Pair("Molester", "en/genres/Molester"),
            Pair("Mom Friend", "en/genres/Mom%20Friend"),
            Pair("Mother", "en/genres/Mother"),
            Pair("Mother Dog", "en/genres/Mother%20Dog"),
            Pair("Mother Friend", "en/genres/Mother%20Friend"),
            Pair("Movement / Fight", "en/genres/Movement%20/%20Fight"),
            Pair("Multi-Person", "en/genres/Multi-Person"),
            Pair("Multiple", "en/genres/Multiple"),
            Pair("Multiple Stories", "en/genres/Multiple%20Stories"),
            Pair("Muscle", "en/genres/Muscle"),
            Pair("Muscle Industry", "en/genres/Muscle%20Industry"),
            Pair("Myodo", "en/genres/Myodo"),
            Pair("Naive", "en/genres/Naive"),
            Pair("Naked Apron", "en/genres/Naked%20Apron"),
            Pair("Naked Clothes", "en/genres/Naked%20Clothes"),
            Pair("Nasty / Hard", "en/genres/Nasty%20/%20Hard"),
            Pair("Nausea", "en/genres/Nausea"),
            Pair("Neat", "en/genres/Neat"),
            Pair("Neat And Clean", "en/genres/Neat%20And%20Clean"),
            Pair("New Daughter / Wife And Child", "en/genres/New%20Daughter%20/%20Wife%20And%20Child"),
            Pair("New Student", "en/genres/New%20Student"),
            Pair("Newcomer Debut", "en/genres/Newcomer%20Debut"),
            Pair("Nice Ass", "en/genres/Nice%20Ass"),
            Pair("Nice Boobs", "en/genres/Nice%20Boobs"),
            Pair("No Underwear", "en/genres/No%20Underwear"),
            Pair("Non-Nude", "en/genres/Non-Nude"),
            Pair("Nose Hook", "en/genres/Nose%20Hook"),
            Pair("Ntr", "en/genres/Ntr"),
            Pair("Nurse", "en/genres/Nurse"),
            Pair("Nursing", "en/genres/Nursing"),
            Pair("Nyotaimori", "en/genres/Nyotaimori"),
            Pair("Office", "en/genres/Office"),
            Pair("Oil Lotion", "en/genres/Oil%20Lotion"),
            Pair("Ol", "en/genres/Ol"),
            Pair("One Piece Dress", "en/genres/One%20Piece%20Dress"),
            Pair("Oral Ejaculation", "en/genres/Oral%20Ejaculation"),
            Pair("Oral Firing", "en/genres/Oral%20Firing"),
            Pair("Oral Sex", "en/genres/Oral%20Sex"),
            Pair("Ordinary Person", "en/genres/Ordinary%20Person"),
            Pair("Orgy", "en/genres/Orgy"),
            Pair("Orgy With Glue! Im Crazy For Multiple Plays!", "en/genres/Orgy%20With%20Glue!%20Im%20Crazy%20For%20Multiple%20Plays!"),
            Pair("Original", "en/genres/Original"),
            Pair("Original Feeling", "en/genres/Original%20Feeling"),
            Pair("Original Works", "en/genres/Original%20Works"),
            Pair("Otaku", "en/genres/Otaku"),
            Pair("Other", "en/genres/Other"),
            Pair("Other Finger", "en/genres/Other%20Finger"),
            Pair("Other Love Affairs", "en/genres/Other%20Love%20Affairs"),
            Pair("Other Student", "en/genres/Other%20Student"),
            Pair("Outdoor Exposure", "en/genres/Outdoor%20Exposure"),
            Pair("Outdoors", "en/genres/Outdoors"),
            Pair("Pantyhose", "en/genres/Pantyhose"),
            Pair("Pantyhose Thing", "en/genres/Pantyhose%20Thing"),
            Pair("Partner Exchange", "en/genres/Partner%20Exchange"),
            Pair("Pee", "en/genres/Pee"),
            Pair("People", "en/genres/People"),
            Pair("Personal Work", "en/genres/Personal%20Work"),
            Pair("Petite", "en/genres/Petite"),
            Pair("Physical Education", "en/genres/Physical%20Education"),
            Pair("Pickup Amateur", "en/genres/Pickup%20Amateur"),
            Pair("Piledriver", "en/genres/Piledriver"),
            Pair("Pink Rotor", "en/genres/Pink%20Rotor"),
            Pair("Pissing", "en/genres/Pissing"),
            Pair("Pissing / Incontinence", "en/genres/Pissing%20/%20Incontinence"),
            Pair("Planning", "en/genres/Planning"),
            Pair("Play", "en/genres/Play"),
            Pair("Plot", "en/genres/Plot"),
            Pair("Pregnant", "en/genres/Pregnant"),
            Pair("Pregnant Woman", "en/genres/Pregnant%20Woman"),
            Pair("Premature Ejaculation", "en/genres/Premature%20Ejaculation"),
            Pair("Prestige 20Th Anniversary Special Project", "en/genres/Prestige%2020Th%20Anniversary%20Special%20Project"),
            Pair("Pretty Girl", "en/genres/Pretty%20Girl"),
            Pair("Princess", "en/genres/Princess"),
            Pair("Private Teacher", "en/genres/Private%20Teacher"),
            Pair("Proboscis", "en/genres/Proboscis"),
            Pair("Promiscuity", "en/genres/Promiscuity"),
            Pair("Promiscuous", "en/genres/Promiscuous"),
            Pair("Prostitute", "en/genres/Prostitute"),
            Pair("Prostitution", "en/genres/Prostitution"),
            Pair("Proud Pussy", "en/genres/Proud%20Pussy"),
            Pair("Pure", "en/genres/Pure"),
            Pair("Queen", "en/genres/Queen"),
            Pair("Racing Girl", "en/genres/Racing%20Girl"),
            Pair("Ranko", "en/genres/Ranko"),
            Pair("Rape", "en/genres/Rape"),
            Pair("Raw Digging", "en/genres/Raw%20Digging"),
            Pair("Realistic Version Of The Game", "en/genres/Realistic%20Version%20Of%20The%20Game"),
            Pair("Receptionist", "en/genres/Receptionist"),
            Pair("Record", "en/genres/Record"),
            Pair("Rejuvenation Massage", "en/genres/Rejuvenation%20Massage"),
            Pair("Reluctance", "en/genres/Reluctance"),
            Pair("Reproduce", "en/genres/Reproduce"),
            Pair("Resort Equipment", "en/genres/Resort%20Equipment"),
            Pair("Restraint", "en/genres/Restraint"),
            Pair("Retreat", "en/genres/Retreat"),
            Pair("Rice Man", "en/genres/Rice%20Man"),
            Pair("Ride", "en/genres/Ride"),
            Pair("Rigidity / Rigid System", "en/genres/Rigidity%20/%20Rigid%20System"),
            Pair("Romantic Comedy", "en/genres/Romantic%20Comedy"),
            Pair("Saddle", "en/genres/Saddle"),
            Pair("Sailor Suit", "en/genres/Sailor%20Suit"),
            Pair("Salt Wipe", "en/genres/Salt%20Wipe"),
            Pair("Same-Sex Love", "en/genres/Same-Sex%20Love"),
            Pair("School Play", "en/genres/School%20Play"),
            Pair("School Swimsuit", "en/genres/School%20Swimsuit"),
            Pair("School Teacher", "en/genres/School%20Teacher"),
            Pair("School Uniform", "en/genres/School%20Uniform"),
            Pair("Schoolgirl", "en/genres/Schoolgirl"),
            Pair("Science Fiction", "en/genres/Science%20Fiction"),
            Pair("Scold", "en/genres/Scold"),
            Pair("Secretary", "en/genres/Secretary"),
            Pair("Selfie", "en/genres/Selfie"),
            Pair("Semen", "en/genres/Semen"),
            Pair("Set Of 10", "en/genres/Set%20Of%2010"),
            Pair("Set Product", "en/genres/Set%20Product"),
            Pair("Sex", "en/genres/Sex"),
            Pair("Sex Education", "en/genres/Sex%20Education"),
            Pair("Sex For Business", "en/genres/Sex%20For%20Business"),
            Pair("Sex Friend", "en/genres/Sex%20Friend"),
            Pair("Sexual Slavery", "en/genres/Sexual%20Slavery"),
            Pair("Sexy", "en/genres/Sexy"),
            Pair("Sexy Legs", "en/genres/Sexy%20Legs"),
            Pair("Sf", "en/genres/Sf"),
            Pair("Shame", "en/genres/Shame"),
            Pair("Shame And Humiliation", "en/genres/Shame%20And%20Humiliation"),
            Pair("Shaving", "en/genres/Shaving"),
            Pair("Shijutakin", "en/genres/Shijutakin"),
            Pair("Shipping", "en/genres/Shipping"),
            Pair("Short Hair", "en/genres/Short%20Hair"),
            Pair("Short Skirt", "en/genres/Short%20Skirt"),
            Pair("Shortcut", "en/genres/Shortcut"),
            Pair("Shortcut Girls! Boyish, But Amazing Sex!", "en/genres/Shortcut%20Girls!%20Boyish,%20But%20Amazing%20Sex!"),
            Pair("Shout Out", "en/genres/Shout%20Out"),
            Pair("Shower", "en/genres/Shower"),
            Pair("Similar", "en/genres/Similar"),
            Pair("Single Work", "en/genres/Single%20Work"),
            Pair("Sister", "en/genres/Sister"),
            Pair("Sistine", "en/genres/Sistine"),
            Pair("Sixty", "en/genres/Sixty"),
            Pair("Skirt", "en/genres/Skirt"),
            Pair("Skirt Mono", "en/genres/Skirt%20Mono"),
            Pair("Slave", "en/genres/Slave"),
            Pair("Slim", "en/genres/Slim"),
            Pair("Slim Pixelated", "en/genres/Slim%20Pixelated"),
            Pair("Slut", "en/genres/Slut"),
            Pair("Sm", "en/genres/Sm"),
            Pair("Small", "en/genres/Small"),
            Pair("Small Breasts", "en/genres/Small%20Breasts"),
            Pair("Small Breasts / Small Breasts", "en/genres/Small%20Breasts%20/%20Small%20Breasts"),
            Pair("Smartphone Recommendation Animation", "en/genres/Smartphone%20Recommendation%20Animation"),
            Pair("Sneak Shots", "en/genres/Sneak%20Shots"),
            Pair("Soapland", "en/genres/Soapland"),
            Pair("Soft Body", "en/genres/Soft%20Body"),
            Pair("Solitary", "en/genres/Solitary"),
            Pair("Solo Work", "en/genres/Solo%20Work"),
            Pair("Sorority", "en/genres/Sorority"),
            Pair("Spanking", "en/genres/Spanking"),
            Pair("Speaking", "en/genres/Speaking"),
            Pair("Special Effects", "en/genres/Special%20Effects"),
            Pair("Sportswear", "en/genres/Sportswear"),
            Pair("Squirting", "en/genres/Squirting"),
            Pair("Staff Push! Amateur Whose Reaction During Sex Is Too Erotic", "en/genres/Staff%20Push!%20Amateur%20Whose%20Reaction%20During%20Sex%20Is%20Too%20Erotic"),
            Pair("Stepmother", "en/genres/Stepmother"),
            Pair("Stewardess Ca", "en/genres/Stewardess%20Ca"),
            Pair("Stewardesses And Flight Attendants", "en/genres/Stewardesses%20And%20Flight%20Attendants"),
            Pair("Stockings", "en/genres/Stockings"),
            Pair("Stool", "en/genres/Stool"),
            Pair("Subjective Perspective", "en/genres/Subjective%20Perspective"),
            Pair("Subjectivity", "en/genres/Subjectivity"),
            Pair("Subordinate Or Colleague", "en/genres/Subordinate%20Or%20Colleague"),
            Pair("Super Breasts", "en/genres/Super%20Breasts"),
            Pair("Surface Area", "en/genres/Surface%20Area"),
            Pair("Surplus Work", "en/genres/Surplus%20Work"),
            Pair("Swallow Sperm", "en/genres/Swallow%20Sperm"),
            Pair("Sweating", "en/genres/Sweating"),
            Pair("Sweaty", "en/genres/Sweaty"),
            Pair("Sweet Ass", "en/genres/Sweet%20Ass"),
            Pair("Swimsuit", "en/genres/Swimsuit"),
            Pair("Swimwear", "en/genres/Swimwear"),
            Pair("Swimwear / School Swimwear", "en/genres/Swimwear%20/%20School%20Swimwear"),
            Pair("Taiwan Model", "en/genres/Taiwan%20Model"),
            Pair("Tall Glamorous", "en/genres/Tall%20Glamorous"),
            Pair("Tall Lady", "en/genres/Tall%20Lady"),
            Pair("Tan", "en/genres/Tan"),
            Pair("Tattoos", "en/genres/Tattoos"),
            Pair("Teacher", "en/genres/Teacher"),
            Pair("Teen (18+)", "en/genres/Teen%20%2818+%29"),
            Pair("Tentacle", "en/genres/Tentacle"),
            Pair("Thanks Offering", "en/genres/Thanks%20Offering"),
            Pair("The Magic Mirror", "en/genres/The%20Magic%20Mirror"),
            Pair("Thirty", "en/genres/Thirty"),
            Pair("Thirty Years Old", "en/genres/Thirty%20Years%20Old"),
            Pair("Tickle", "en/genres/Tickle"),
            Pair("Tied Up", "en/genres/Tied%20Up"),
            Pair("Time Stops", "en/genres/Time%20Stops"),
            Pair("Tit Job", "en/genres/Tit%20Job"),
            Pair("Tits", "en/genres/Tits"),
            Pair("Together", "en/genres/Together"),
            Pair("Tokusatsu", "en/genres/Tokusatsu"),
            Pair("Tool", "en/genres/Tool"),
            Pair("Torture", "en/genres/Torture"),
            Pair("Toy", "en/genres/Toy"),
            Pair("Training", "en/genres/Training"),
            Pair("Transform To Heroine", "en/genres/Transform%20To%20Heroine"),
            Pair("Transformation", "en/genres/Transformation"),
            Pair("Transgender", "en/genres/Transgender"),
            Pair("Transsexual", "en/genres/Transsexual"),
            Pair("Transsexuals", "en/genres/Transsexuals"),
            Pair("Travel", "en/genres/Travel"),
            Pair("Trip", "en/genres/Trip"),
            Pair("Turn Number", "en/genres/Turn%20Number"),
            Pair("Ultra Slim Pixelated", "en/genres/Ultra%20Slim%20Pixelated"),
            Pair("Unavoidable", "en/genres/Unavoidable"),
            Pair("Uncensored Leak", "en/uncensored-leak"),
            Pair("Underwear", "en/genres/Underwear"),
            Pair("Uniform", "en/genres/Uniform"),
            Pair("Urinate", "en/genres/Urinate"),
            Pair("Urination", "en/genres/Urination"),
            Pair("Urination / Incontinence", "en/genres/Urination%20/%20Incontinence"),
            Pair("Urination And Incontinence", "en/genres/Urination%20And%20Incontinence"),
            Pair("Uterus", "en/genres/Uterus"),
            Pair("Various Occupations", "en/genres/Various%20Occupations"),
            Pair("Various Workers", "en/genres/Various%20Workers"),
            Pair("Vibrating Egg", "en/genres/Vibrating%20Egg"),
            Pair("Vibrator", "en/genres/Vibrator"),
            Pair("Vigne", "en/genres/Vigne"),
            Pair("Virgin", "en/genres/Virgin"),
            Pair("Virgin Man", "en/genres/Virgin%20Man"),
            Pair("Virgin Thing", "en/genres/Virgin%20Thing"),
            Pair("Vomit", "en/genres/Vomit"),
            Pair("Voyeur", "en/genres/Voyeur"),
            Pair("Voyeur / Peeping", "en/genres/Voyeur%20/%20Peeping"),
            Pair("VR", "en/genres/VR"),
            Pair("Vr", "en/genres/Vr"),
            Pair("Waitress", "en/genres/Waitress"),
            Pair("White Skin", "en/genres/White%20Skin"),
            Pair("Whitening", "en/genres/Whitening"),
            Pair("Whites", "en/genres/Whites"),
            Pair("Widow", "en/genres/Widow"),
            Pair("Wife", "en/genres/Wife"),
            Pair("Witch", "en/genres/Witch"),
            Pair("With Bonus Video Only For Mgs", "en/genres/With%20Bonus%20Video%20Only%20For%20Mgs"),
            Pair("Words Blame", "en/genres/Words%20Blame"),
            Pair("Yariman Gal Bitch!", "en/genres/Yariman%20Gal%20Bitch!"),
            Pair("Yoga", "en/genres/Yoga"),
            Pair("Yokui", "en/genres/Yokui"),
            Pair("Young", "en/genres/Young"),
            Pair("Young Wife", "en/genres/Young%20Wife"),
            Pair("Yukata", "en/genres/Yukata"),
            Pair("Yukata / Kimono", "en/genres/Yukata%20/%20Kimono"),
            Pair("偷窥", "en/genres/%E5%81%B7%E7%AA%A5"),
            Pair("刨面包", "en/genres/%E5%88%A8%E9%9D%A2%E5%8C%85"),
            Pair("拖", "en/genres/%E6%8B%96"),
        )
    }
}

fun getFilters() = AnimeFilterList(
    SortFilter(),
    GenreList(),
    AnimeFilter.Separator(),
    AnimeFilter.Header("Genre filters ignored with text search!!"),
)
