ext {
    extName = 'Cuevana'
    extClass = '.CuevanaFactory'
    extVersionCode = 68
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(':lib:streamwishextractor'))
    implementation(project(':lib:filemoonextractor'))
    implementation(project(':lib:youruploadextractor'))
    implementation(project(':lib:streamtapeextractor'))
    implementation(project(':lib:doodextractor'))
    implementation(project(':lib:voeextractor'))
    implementation(project(':lib:okruextractor'))
    implementation(project(':lib:universalextractor'))
}
