ext {
    extName = 'Anime-Sama'
    extClass = '.AnimeSama'
    extVersionCode = 31
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(':lib:sibnetextractor'))
    implementation(project(':lib:vkextractor'))
    implementation(project(':lib:sendvidextractor'))
    implementation(project(':lib:vidmolyextractor'))
    implementation(project(':lib:vidhideextractor'))
    implementation(project(':lib:uqloadextractor'))
    implementation(project(':lib:youruploadextractor'))
    implementation(project(':lib:universalextractor'))
    implementation(project(':lib:embed4meextractor'))
}
