ext {
    extName = 'AnimeQ'
    extClass = '.AnimeQ'
    themePkg = 'dooplay'
    baseUrl = 'https://animeq.blog'
    overrideVersionCode = 3
    isNsfw = true
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(":lib:bloggerextractor"))
    implementation(project(":lib:playlistutils"))
}
