ext {
    extName = 'TVAnime'
    extClass = '.TVAnime'
    libVersion = 16
    extVersionCode = 50
    isNsfw = true
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(':lib:voeextractor'))
    implementation(project(':lib:mp4uploadextractor'))
    implementation(project(':lib:youruploadextractor'))
    implementation(project(':lib:streamtapeextractor'))
    implementation(project(':lib:vidhideextractor'))
    implementation(project(':lib:filemoonextractor'))
    implementation(project(':lib:megaextractor'))
    implementation(project(':lib:universalextractor'))
}
