ext {
    extName = 'AnimesHentaiBiz'
    extClass = '.AnimesHentaiBiz'
    baseUrl = 'https://animeshentai.biz'
    extVersionCode = 1
    isNsfw = true
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(":core"))
    implementation(libs.bundles.common)
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.9.24")
}
