ext {
    extName = 'AnimesHentaiBiz'
    extClass = '.AnimesHentaiBiz'
    extVersionCode = 1
    isNsfw = true
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    // Nenhuma dependência extra necessária para esta extensão.
    // O plugin legado já inclui OkHttp, Jsoup, Kotlin stdlib e a API do Aniyomi.
}
