ext {
    libVersion = 16
    extName = 'Wiflix'
    extClass = '.Wiflix'
    themePkg = 'datalifeengine'
    baseUrl = 'https://flemmix.eu'
    overrideVersionCode = 30
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(':lib:doodextractor'))
    implementation(project(':lib:vidoextractor'))
    implementation(project(':lib:uqloadextractor'))
    implementation(project(':lib:streamdavextractor'))
    implementation(project(':lib:vudeoextractor'))
    implementation(project(':lib:vidhideextractor'))
    implementation(project(':lib:upstreamextractor'))
    implementation(project(':lib:voeextractor'))
}
