ext {
    extName = 'StreamingCommunity'
    extClass = '.StreamingCommunityFactory'
    extVersionCode = 23
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(":lib:playlistutils"))
    implementation(project(":lib:i18n"))
    implementation("com.github.komikku-app.nanohttpd:nanohttpd:gradle-upgrade-SNAPSHOT")
}
