package eu.kanade.tachiyomi.animeextension.en.anidb

import eu.kanade.tachiyomi.animesource.model.AnimeFilter
import java.util.Calendar

object Filters {

    class TypeFilter : UriPartFilter("Type", TYPES) {
        companion object {
            val TYPES = arrayOf(
                Pair("All", ""),
                Pair("Movie", "Movie"),
                Pair("Music", "Music"),
                Pair("ONA", "ONA"),
                Pair("OVA", "OVA"),
                Pair("Special", "Special"),
                Pair("TV", "TV"),
            )
        }
    }

    class StatusFilter : UriPartFilter("Status", STATUSES) {
        companion object {
            val STATUSES = arrayOf(
                Pair("All", ""),
                Pair("Currently Airing", "Currently Airing"),
                Pair("Finished Airing", "Finished Airing"),
            )
        }
    }

    class SeasonFilter : UriPartFilter("Season", SEASONS) {
        companion object {
            val SEASONS = arrayOf(
                Pair("All", ""),
                Pair("Spring", "spring"),
                Pair("Summer", "summer"),
                Pair("Fall", "fall"),
                Pair("Winter", "winter"),
            )
        }
    }

    class YearFilter : UriPartFilter("Year", YEARS) {
        companion object {
            private val CURRENT_YEAR by lazy {
                Calendar.getInstance().get(Calendar.YEAR)
            }

            val YEARS = buildList {
                add(Pair("All", ""))
                addAll((CURRENT_YEAR downTo 1968).map { Pair(it.toString(), it.toString()) })
                add(Pair("1925", "1925"))
            }.toTypedArray()
        }
    }

    class DemographicFilter : UriPartFilter("Demographic", DEMOGRAPHICS) {
        companion object {
            val DEMOGRAPHICS = arrayOf(
                Pair("All", ""),
                Pair("Shounen", "1"),
                Pair("Seinen", "2"),
                Pair("Shoujo", "5"),
                Pair("Kids", "4"),
                Pair("Josei", "3"),
            )
        }
    }

    class GenreFilter : UriPartFilter("Genre", GENRES) {
        companion object {
            val GENRES = arrayOf(
                Pair("All", ""),
                Pair("Action", "1"),
                Pair("Adventure", "3"),
                Pair("Avant Garde", "19"),
                Pair("Award Winning", "12"),
                Pair("Boys Love", "16"),
                Pair("Comedy", "5"),
                Pair("Drama", "2"),
                Pair("Ecchi", "13"),
                Pair("Erotica", "17"),
                Pair("Fantasy", "4"),
                Pair("Girls Love", "20"),
                Pair("Gourmet", "8"),
                Pair("Hentai", "15"),
                Pair("Horror", "21"),
                Pair("Mystery", "7"),
                Pair("Romance", "14"),
                Pair("Sci-Fi", "6"),
                Pair("Slice of Life", "9"),
                Pair("Sports", "11"),
                Pair("Supernatural", "10"),
                Pair("Suspense", "18"),
            )
        }
    }

    class ThemeFilter : UriPartFilter("Theme", THEMES) {
        companion object {
            val THEMES = arrayOf(
                Pair("All", ""),
                Pair("Adult Cast", "13"),
                Pair("Anthropomorphic", "34"),
                Pair("CGDCT", "35"),
                Pair("Childcare", "31"),
                Pair("Combat Sports", "5"),
                Pair("Comedy", "56"),
                Pair("Crossdressing", "36"),
                Pair("Delinquents", "46"),
                Pair("Detective", "40"),
                Pair("Educational", "53"),
                Pair("Gag Humor", "38"),
                Pair("Gore", "42"),
                Pair("Harem", "12"),
                Pair("High Stakes Game", "52"),
                Pair("Historical", "24"),
                Pair("Idols (Female)", "18"),
                Pair("Idols (Male)", "50"),
                Pair("Isekai", "9"),
                Pair("Iyashikei", "47"),
                Pair("Love Polygon", "33"),
                Pair("Love Status Quo", "45"),
                Pair("Magical Sex Shift", "51"),
                Pair("Mahou Shoujo", "41"),
                Pair("Martial Arts", "39"),
                Pair("Mecha", "23"),
                Pair("Medical", "48"),
                Pair("Military", "10"),
                Pair("Music", "19"),
                Pair("Mythology", "4"),
                Pair("Organized Crime", "25"),
                Pair("Otaku Culture", "14"),
                Pair("Parody", "3"),
                Pair("Performing Arts", "32"),
                Pair("Pets", "29"),
                Pair("Psychological", "20"),
                Pair("Racing", "49"),
                Pair("Reincarnation", "7"),
                Pair("Reverse Harem", "11"),
                Pair("Romantic Subtext", "37"),
                Pair("Samurai", "26"),
                Pair("School", "6"),
                Pair("Showbiz", "8"),
                Pair("Space", "44"),
                Pair("Strategy Game", "43"),
                Pair("Super Power", "1"),
                Pair("Supernatural", "54"),
                Pair("Survival", "21"),
                Pair("Suspense", "55"),
                Pair("Team Sports", "17"),
                Pair("Time Travel", "15"),
                Pair("Urban Fantasy", "27"),
                Pair("Vampire", "28"),
                Pair("Video Game", "2"),
                Pair("Villainess", "22"),
                Pair("Visual Arts", "30"),
                Pair("Workplace", "16"),
            )
        }
    }

    class StudioFilter : UriPartFilter("Studio", STUDIOS) {
        companion object {
            val STUDIOS = arrayOf(
                Pair("All", ""),
                Pair("100studio", "44"),
                Pair("10Gauge", "514"),
                Pair("3D", "209"),
                Pair("5 Inc.", "263"),
                Pair("8bit", "1"),
                Pair("A-1 Pictures", "24"),
                Pair("A-Line", "430"),
                Pair("A-Real", "307"),
                Pair("A.C.G.T.", "170"),
                Pair("A4works", "198"),
                Pair("ABJ COMPANY", "326"),
                Pair("Academy Productions", "525"),
                Pair("Acca effe", "477"),
                Pair("Actas", "219"),
                Pair("Adonero", "244"),
                Pair("Ai Si Animation Studio", "533"),
                Pair("AIC", "75"),
                Pair("AIC ASTA", "143"),
                Pair("AIC Build", "305"),
                Pair("AIC Classic", "254"),
                Pair("AIC PLUS+", "140"),
                Pair("AIC Spirits", "195"),
                Pair("Ajia-do", "62"),
                Pair("Akatsuki", "275"),
                Pair("Albacrow", "188"),
                Pair("Alfred Imageworks", "506"),
                Pair("Amber Film Works", "284"),
                Pair("Anima", "5"),
                Pair("Anima&Co.", "475"),
                Pair("Animaruya", "502"),
                Pair("animate Film", "104"),
                Pair("Animation Do", "280"),
                Pair("Animation Planet", "464"),
                Pair("Animation Staff Room", "435"),
                Pair("animation studio42", "343"),
                Pair("Anime R", "249"),
                Pair("Ankama Animations", "393"),
                Pair("Anpro", "196"),
                Pair("APPP", "272"),
                Pair("AQUA ARIS", "206"),
                Pair("Arcs Create", "438"),
                Pair("ARECT", "191"),
                Pair("Ark", "531"),
                Pair("Arms", "84"),
                Pair("Artland", "126"),
                Pair("Artmic", "238"),
                Pair("Arvo Animation", "60"),
                Pair("Asahi Production", "45"),
                Pair("Ascension", "223"),
                Pair("Ashi Productions", "26"),
                Pair("ASK Animation Studio", "501"),
                Pair("Asmik Ace", "240"),
                Pair("asread.", "55"),
                Pair("Atelier Peuplier", "335"),
                Pair("Atelier Pontdarc", "291"),
                Pair("AtoriE", "561"),
                Pair("Aubeck", "286"),
                Pair("Aura Studio", "552"),
                Pair("AXsiZ", "330"),
                Pair("B&T", "171"),
                Pair("B.CMAY PICTURES", "70"),
                Pair("B.COOL STUDIO", "513"),
                Pair("Bakken Record", "8"),
                Pair("Bandai Namco Pictures", "89"),
                Pair("Barnum Studio", "440"),
                Pair("Bee Media", "293"),
                Pair("Bee Train", "2"),
                Pair("Bellnox Films", "494"),
                Pair("BENTEN Film", "437"),
                Pair("BeSTACK", "489"),
                Pair("Bibury Animation CG", "174"),
                Pair("Bibury Animation Studios", "145"),
                Pair("Big Firebird Culture", "162"),
                Pair("Blade", "212"),
                Pair("Blaze Studio", "190"),
                Pair("BloomZ", "342"),
                Pair("Blue bread", "427"),
                Pair("Bones", "72"),
                Pair("Bones Film", "233"),
                Pair("Bouncy", "322"),
                Pair("Brain's Base", "97"),
                Pair("Bridge", "151"),
                Pair("Brio Animation", "371"),
                Pair("Buemon", "391"),
                Pair("BUG FILMS", "534"),
                Pair("C-Station", "92"),
                Pair("C2C", "309"),
                Pair("CALF", "536"),
                Pair("CGCG Studio", "256"),
                Pair("Chaos Project", "225"),
                Pair("Charaction", "245"),
                Pair("Children's Playground Entertainment", "314"),
                Pair("CLAP", "446"),
                Pair("Climax Studio", "380"),
                Pair("Cloud Hearts", "487"),
                Pair("CloverWorks", "76"),
                Pair("CMC Media", "266"),
                Pair("Cocktail Media", "518"),
                Pair("Colored Pencil Animation", "496"),
                Pair("Colored Pencil Animation Japan", "422"),
                Pair("CoMix Wave Films", "27"),
                Pair("CompTown", "315"),
                Pair("Connect", "115"),
                Pair("Craftar Studios", "339"),
                Pair("Creators in Pack", "179"),
                Pair("Crew-Cell", "403"),
                Pair("Cue", "361"),
                Pair("CyberConnect2", "3"),
                Pair("Cyclone Graphics", "530"),
                Pair("CygamesPictures", "127"),
                Pair("Cypic", "554"),
                Pair("Daewon Media", "260"),
                Pair("Dai Nippon Printing", "547"),
                Pair("DandeLion Animation Studio", "95"),
                Pair("Daume", "192"),
                Pair("David Production", "22"),
                Pair("DAX Production", "395"),
                Pair("Deck", "463"),
                Pair("Digital Network Animation", "331"),
                Pair("Diomedéa", "78"),
                Pair("DLE", "253"),
                Pair("DMM.futureworks", "154"),
                Pair("Doga Kobo", "9"),
                Pair("domerica", "267"),
                Pair("Dongwoo A&E", "321"),
                Pair("Doraku", "258"),
                Pair("DR Movie", "505"),
                Pair("DRAWIZ", "419"),
                Pair("Drive", "81"),
                Pair("drop", "300"),
                Pair("dwarf", "345"),
                Pair("Dynamo Pictures", "138"),
                Pair("E&G Films", "470"),
                Pair("E&H Production", "193"),
                Pair("East Fish Studio", "36"),
                Pair("Echoes", "439"),
                Pair("Egg Firm", "462"),
                Pair("Eiken", "184"),
                Pair("EKACHI EPILKA", "19"),
                Pair("Elias", "436"),
                Pair("Emon", "507"),
                Pair("EMT Squared", "41"),
                Pair("Encourage Films", "100"),
                Pair("ENGI", "281"),
                Pair("Enishiya", "485"),
                Pair("EOTA", "402"),
                Pair("Equator", "546"),
                Pair("evg", "358"),
                Pair("Ezόla", "131"),
                Pair("Fanworks", "74"),
                Pair("feel.", "172"),
                Pair("Felix Film", "48"),
                Pair("Fenz", "105"),
                Pair("Fever Creations", "484"),
                Pair("Fifth Avenue", "537"),
                Pair("FILMONY", "441"),
                Pair("Flagship Line", "407"),
                Pair("Flat Studio", "479"),
                Pair("Flying Ship Studio", "199"),
                Pair("Foch Film", "282"),
                Pair("Fortes", "449"),
                Pair("Fortiche Production", "130"),
                Pair("Four Some", "357"),
                Pair("Fugaku", "243"),
                Pair("G&G Direction", "468"),
                Pair("G-angle", "306"),
                Pair("Ga-Crew", "452"),
                Pair("Gaina", "148"),
                Pair("Gainax", "117"),
                Pair("Gainax Kyoto", "526"),
                Pair("Gallop", "183"),
                Pair("Gambit", "491"),
                Pair("GANSIS", "414"),
                Pair("GARDEN Culture", "248"),
                Pair("GARDEN LODGE", "540"),
                Pair("Gathering", "66"),
                Pair("Geek Toys", "235"),
                Pair("Gekkou", "57"),
                Pair("GEMBA", "169"),
                Pair("Geno Studio", "301"),
                Pair("Gift-o’-Animation", "201"),
                Pair("Giga Production", "478"),
                Pair("GoHands", "226"),
                Pair("Gonzo", "21"),
                Pair("Gosay Studio", "264"),
                Pair("Graphinica", "123"),
                Pair("Grass", "558"),
                Pair("Gravity Well", "372"),
                Pair("GRIZZLY", "524"),
                Pair("Group TAC", "129"),
                Pair("Grouper Productions", "553"),
                Pair("Guangzhou Liu Ling Yi", "551"),
                Pair("HAL Film Maker", "132"),
                Pair("Haoliners Animation", "35"),
                Pair("Hayabusa Film", "208"),
                Pair("Heart & Soul Animation", "373"),
                Pair("helo.inc", "398"),
                Pair("Hero", "563"),
                Pair("HMCH", "106"),
                Pair("Hoods Entertainment", "47"),
                Pair("HORNETS", "30"),
                Pair("Hotline", "474"),
                Pair("HOTZIPANG", "85"),
                Pair("HuaMei Animation", "79"),
                Pair("Hurray!", "43"),
                Pair("Husio Studio", "469"),
                Pair("I was a Ballerina", "425"),
                Pair("I.Gzwei", "173"),
                Pair("Idea Factory", "490"),
                Pair("ILCA", "418"),
                Pair("ILCASHIPS", "512"),
                Pair("Imageworks Studio", "12"),
                Pair("Imagica Infos", "11"),
                Pair("IMAGICA Lab.", "137"),
                Pair("Imagin", "455"),
                Pair("Imagineer", "482"),
                Pair("Indivision", "20"),
                Pair("Issen", "153"),
                Pair("J.C.Staff", "23"),
                Pair("Japan Vistec", "297"),
                Pair("JCF", "467"),
                Pair("Jinnis Animation Studios", "334"),
                Pair("Jumondou", "247"),
                Pair("Jumonji", "96"),
                Pair("Juvenage", "368"),
                Pair("K-Factory", "374"),
                Pair("Kachidoki Studio", "119"),
                Pair("Kachigarasu", "498"),
                Pair("Kamikaze Douga", "289"),
                Pair("Kanaban Graphics", "336"),
                Pair("Kazami Gakuen Koushiki Douga-bu", "231"),
                Pair("Kenji Studio", "224"),
                Pair("Khara", "261"),
                Pair("Kigumi", "458"),
                Pair("Kinema Citrus", "4"),
                Pair("Kitty Film Mitaka Studio", "375"),
                Pair("Knack Productions", "211"),
                Pair("KOO-KI", "480"),
                Pair("KSS", "388"),
                Pair("Kung Fu Frog Animation", "434"),
                Pair("Kyoto Animation", "63"),
                Pair("Kyotoma", "348"),
                Pair("l-a-unch・BOX", "189"),
                Pair("LAN Studio", "49"),
                Pair("LandQ studios", "136"),
                Pair("Lapin Track", "259"),
                Pair("Larx Entertainment", "360"),
                Pair("Lay-duce", "10"),
                Pair("Lerche", "87"),
                Pair("Lesprit", "120"),
                Pair("Liber", "157"),
                Pair("LICO", "542"),
                Pair("Lide", "527"),
                Pair("LIDENFILMS", "7"),
                Pair("Life Work", "541"),
                Pair("Light Chaser Animation Studios", "415"),
                Pair("Lingsanwu Animation", "538"),
                Pair("LinQ", "397"),
                Pair("Live2D Creative Studio", "492"),
                Pair("Liyu Culture", "493"),
                Pair("Locus Corporation", "549"),
                Pair("LX Animation Studio", "495"),
                Pair("lxtl", "408"),
                Pair("Lyrics", "25"),
                Pair("L²Studio", "562"),
                Pair("M.S.C", "221"),
                Pair("Madhouse", "51"),
                Pair("Magia Doraglier", "410"),
                Pair("Magic Bus", "59"),
                Pair("Maho Film", "58"),
                Pair("Makaria", "252"),
                Pair("Manga Productions", "283"),
                Pair("Manglobe", "237"),
                Pair("MAPPA", "108"),
                Pair("Marone", "323"),
                Pair("maroyaka", "186"),
                Pair("Maru Animation", "451"),
                Pair("Marvelous Entertainment", "90"),
                Pair("Marvy Jack", "329"),
                Pair("Marza Animation Planet", "213"),
                Pair("MASTER LIGHTS", "473"),
                Pair("MAT", "215"),
                Pair("Meruhensha", "316"),
                Pair("Millepensee", "168"),
                Pair("Mimoid", "444"),
                Pair("Minami Machi Bugyousho", "516"),
                Pair("Miyu Productions", "294"),
                Pair("monofilmo", "319"),
                Pair("MontBlanc Pictures", "274"),
                Pair("Mook DLE", "456"),
                Pair("Mushi Production", "320"),
                Pair("Namu Animation", "50"),
                Pair("NAZ", "116"),
                Pair("Newon", "557"),
                Pair("Nexus", "214"),
                Pair("NHK", "285"),
                Pair("Nice Boat Animation", "532"),
                Pair("Nichicaline", "556"),
                Pair("Nihon Ad Systems", "519"),
                Pair("Nippon Animation", "42"),
                Pair("Nippon Ramayana Film", "450"),
                Pair("Nomad", "102"),
                Pair("Nut", "180"),
                Pair("Nyan Pollution", "242"),
                Pair("October Media", "413"),
                Pair("Office Academy", "161"),
                Pair("Office DCI", "528"),
                Pair("Office No. 8", "432"),
                Pair("Office Nobu", "349"),
                Pair("Oh! Production", "370"),
                Pair("Okuruto Noboru", "39"),
                Pair("OLM", "17"),
                Pair("OLM Digital", "428"),
                Pair("Orange", "163"),
                Pair("Ordet", "175"),
                Pair("OZ", "461"),
                Pair("P.A. Works", "53"),
                Pair("P.I.C.S.", "423"),
                Pair("Painted Blade Studio", "265"),
                Pair("Palm Studio", "156"),
                Pair("Pancake", "443"),
                Pair("Pandanium", "548"),
                Pair("Paper Plane Animation Studio", "421"),
                Pair("Passione", "207"),
                Pair("Pastel", "340"),
                Pair("Pb Animation", "471"),
                Pair("Pepper Conpanna", "448"),
                Pair("Phoenix Entertainment", "295"),
                Pair("Picante Circus", "559"),
                Pair("Picona", "394"),
                Pair("Picture Magic", "362"),
                Pair("Pie in the sky", "325"),
                Pair("Pierrot Films", "178"),
                Pair("Pierrot Plus", "165"),
                Pair("PINE JAM", "6"),
                Pair("Planet Cartoon", "483"),
                Pair("Platinum Vision", "218"),
                Pair("Plum", "365"),
                Pair("Polygon Pictures", "91"),
                Pair("PP Project", "352"),
                Pair("PRA", "31"),
                Pair("Primastea", "369"),
                Pair("PrimeTime", "385"),
                Pair("Production +h.", "236"),
                Pair("production doA", "341"),
                Pair("Production GoodBook", "273"),
                Pair("Production I.G", "52"),
                Pair("Production IMS", "80"),
                Pair("Production Reed", "230"),
                Pair("Project No.9", "16"),
                Pair("Project Studio Q", "476"),
                Pair("Project Team Argos", "182"),
                Pair("Psyde Kick Studio", "564"),
                Pair("Purple Cow Studio Japan", "433"),
                Pair("Qiyuan Yinghua", "504"),
                Pair("qmotri", "377"),
                Pair("Quad", "308"),
                Pair("Qualia Animation", "332"),
                Pair("Qubic Pictures", "255"),
                Pair("Quebico", "454"),
                Pair("Qzil.la", "210"),
                Pair("Radix", "113"),
                Pair("Raiose", "216"),
                Pair("Red Dog Culture House", "317"),
                Pair("Reirs", "396"),
                Pair("Remic", "453"),
                Pair("Revoroot", "149"),
                Pair("Rising Force", "121"),
                Pair("Robot Communications", "67"),
                Pair("Rock'n Roll Mountain", "15"),
                Pair("ROLL2", "381"),
                Pair("S.o.K", "409"),
                Pair("Saber Project", "488"),
                Pair("Saber Works", "166"),
                Pair("Saetta", "347"),
                Pair("SAFEHOUSE", "399"),
                Pair("Sakura Create", "356"),
                Pair("Samsara Animation Studio", "277"),
                Pair("San-X", "431"),
                Pair("SANZIGEN", "125"),
                Pair("Satelight", "33"),
                Pair("Science SARU", "234"),
                Pair("Scooter Films", "344"),
                Pair("Seven", "88"),
                Pair("Seven Arcs", "139"),
                Pair("Seven Arcs Pictures", "158"),
                Pair("Seven Stone Entertainment", "111"),
                Pair("Shaft", "56"),
                Pair("Sharefun Studio", "465"),
                Pair("Shengying Animation", "246"),
                Pair("Shin-Ei Animation", "38"),
                Pair("Shinkuukan", "515"),
                Pair("Shirogumi", "229"),
                Pair("Shogakukan Music & Digital Entertainment", "355"),
                Pair("Shuka", "32"),
                Pair("Signal.MD", "142"),
                Pair("Silver", "18"),
                Pair("SILVER LINK.", "64"),
                Pair("Skyloong", "500"),
                Pair("Soft Garage", "28"),
                Pair("Soigne", "187"),
                Pair("soket", "185"),
                Pair("Sola Digital Arts", "176"),
                Pair("Sola Entertainment", "503"),
                Pair("Sotsu", "416"),
                Pair("Space Neko Company", "290"),
                Pair("Sparkly Key Animation Studio", "481"),
                Pair("Sprite Animation Studios", "429"),
                Pair("Square Enix Visual Works", "269"),
                Pair("Square Pictures", "270"),
                Pair("Staple Entertainment", "34"),
                Pair("StarLink", "303"),
                Pair("Steve N' Steven", "346"),
                Pair("Stingray", "197"),
                Pair("Strawberry Meets Pictures", "292"),
                Pair("Studio 3Hz", "73"),
                Pair("Studio 4°C", "118"),
                Pair("Studio A-CAT", "110"),
                Pair("Studio Add", "510"),
                Pair("Studio Animal", "164"),
                Pair("Studio Barcelona", "366"),
                Pair("Studio Bind", "276"),
                Pair("Studio Blanc.", "144"),
                Pair("Studio CANDY BOX", "146"),
                Pair("Studio Chizu", "167"),
                Pair("Studio Chromato", "227"),
                Pair("Studio Clutch", "417"),
                Pair("Studio Colorido", "68"),
                Pair("Studio Comet", "61"),
                Pair("Studio Crocodile", "521"),
                Pair("Studio Curtain", "250"),
                Pair("Studio Dadashow", "337"),
                Pair("Studio Deen", "13"),
                Pair("Studio DURIAN", "378"),
                Pair("Studio Eek", "555"),
                Pair("Studio Elle", "296"),
                Pair("Studio Fantasia", "103"),
                Pair("Studio Flad", "107"),
                Pair("Studio Fusion", "390"),
                Pair("Studio Gazelle", "239"),
                Pair("Studio Ghibli", "203"),
                Pair("Studio Goindol", "400"),
                Pair("Studio Gokumi", "71"),
                Pair("Studio GOONEYS", "442"),
                Pair("Studio Gram", "405"),
                Pair("Studio Graph77", "486"),
                Pair("Studio Hibari", "220"),
                Pair("Studio Hokiboshi", "241"),
                Pair("Studio Jemi", "202"),
                Pair("Studio Junio", "459"),
                Pair("Studio Kafka", "401"),
                Pair("Studio KAI", "29"),
                Pair("Studio Kingyoiro", "566"),
                Pair("Studio Kyuuma", "310"),
                Pair("Studio LEO", "387"),
                Pair("Studio Lings", "382"),
                Pair("Studio Live", "304"),
                Pair("Studio M2", "424"),
                Pair("Studio Massket", "509"),
                Pair("Studio Matrix", "302"),
                Pair("Studio Mir", "379"),
                Pair("Studio Moe", "383"),
                Pair("Studio Moriken", "529"),
                Pair("studio MOTHER", "134"),
                Pair("Studio N", "517"),
                Pair("Studio Nanahoshi", "367"),
                Pair("Studio Outrigger", "257"),
                Pair("Studio Palette", "354"),
                Pair("Studio Pastoral", "384"),
                Pair("Studio Pierrot", "99"),
                Pair("Studio Polon", "338"),
                Pair("Studio Ponoc", "389"),
                Pair("Studio PuYUKAI", "299"),
                Pair("Studio Ranmaru", "312"),
                Pair("Studio Rikka", "128"),
                Pair("Studio Sign", "364"),
                Pair("Studio Signpost", "363"),
                Pair("Studio Take Off", "539"),
                Pair("Studio VOLN", "150"),
                Pair("Sublimation", "251"),
                Pair("Sunrise", "65"),
                Pair("Sunrise Beyond", "109"),
                Pair("SynergySP", "37"),
                Pair("Takahashi Studio", "324"),
                Pair("Tatsunoko Production", "46"),
                Pair("Team TillDawn", "535"),
                Pair("team Yamahitsuji", "194"),
                Pair("Team YokkyuFuman", "287"),
                Pair("teamKG", "177"),
                Pair("Tear Studio", "279"),
                Pair("Teddy", "333"),
                Pair("Telecom Animation Film", "141"),
                Pair("Tengu Kobo", "412"),
                Pair("Tezuka Productions", "83"),
                Pair("The Answer Studio", "122"),
                Pair("Thundray", "205"),
                Pair("TMS Entertainment", "82"),
                Pair("TNK", "94"),
                Pair("Toei Animation", "14"),
                Pair("TOHO animation STUDIO", "271"),
                Pair("Toho Interactive Animation", "420"),
                Pair("Tokyo Kids", "288"),
                Pair("Tokyo Movie Shinsha", "77"),
                Pair("Tomason", "278"),
                Pair("Tomovies", "350"),
                Pair("Topcraft", "411"),
                Pair("Trans Arts", "376"),
                Pair("TRCARTOON", "204"),
                Pair("Triangle Staff", "222"),
                Pair("TriF Studio", "392"),
                Pair("Trigger", "181"),
                Pair("Trinet Entertainment", "520"),
                Pair("TrioPen Studio", "112"),
                Pair("TROYCA", "101"),
                Pair("Tsuchida Productions", "200"),
                Pair("Tsumugi Akita Animation Lab", "328"),
                Pair("Twilight Studio", "522"),
                Pair("Twilight Town", "466"),
                Pair("TYO Animations", "133"),
                Pair("Typhoon Graphics", "124"),
                Pair("UchuPeople", "447"),
                Pair("ufotable", "228"),
                Pair("UKA", "147"),
                Pair("Ultra Super Pictures", "313"),
                Pair("Unend", "353"),
                Pair("UWAN Pictures", "327"),
                Pair("Vega Entertainment", "160"),
                Pair("Venet", "311"),
                Pair("Viewworks", "472"),
                Pair("Visual 80", "499"),
                Pair("Visual Flight", "262"),
                Pair("Voil", "54"),
                Pair("W-Toon Studio", "232"),
                Pair("WAO World", "69"),
                Pair("Wawayu Animation", "217"),
                Pair("White Fox", "93"),
                Pair("Wit Studio", "86"),
                Pair("Wolfsbane", "155"),
                Pair("WonderLand", "508"),
                Pair("Wuhu Studio", "550"),
                Pair("Xebec", "152"),
                Pair("XEBEC M2", "545"),
                Pair("XFLAG", "268"),
                Pair("XFLAG Pictures", "404"),
                Pair("Yamato Works", "351"),
                Pair("Yaoyorozu", "359"),
                Pair("Yasuda Genshou Studio by Xenotoon", "386"),
                Pair("yell", "511"),
                Pair("Yokohama Animation Lab", "318"),
                Pair("Yostar Pictures", "135"),
                Pair("You Hu Wenhua", "457"),
                Pair("Yumeta Company", "98"),
                Pair("Zelico Film", "497"),
                Pair("Zero-G", "159"),
                Pair("Zero-G Room", "460"),
                Pair("Zexcs", "40"),
                Pair("ZG-R", "565"),
            )
        }
    }

    class SortFilter : UriPartFilter("Sort by", SORTS) {
        companion object {
            val SORTS = arrayOf(
                Pair("Trending", "order_trending"),
                Pair("Top Rated", "order_top"),
                Pair("Latest Updated", "order_updated"),
                Pair("Most Popular", "order_popular"),
                Pair("Most Favorited", "order_favorite"),
                Pair("Top Airing", "order_top_airing"),
                Pair("Title A-Z", "title"),
                Pair("Newest First", "aired_start"),
            )
        }
    }

    open class UriPartFilter(
        displayName: String,
        private val vals: Array<Pair<String, String>>,
    ) : AnimeFilter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
        fun toUriPart() = vals[state].second
        fun isDefault() = state == 0
    }
}
