ext {
    extName = 'OtakuDesu'
    extClass = '.OtakuDesu'
    extVersionCode = 44
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(":lib:bloggerextractor"))
    implementation(project(":lib:mp4uploadextractor"))
    implementation(project(":lib:streamwishextractor"))
    implementation(project(":lib:vidhideextractor"))
    implementation(project(":lib:youruploadextractor"))
}
