package eu.kanade.tachiyomi.animeextension.all.javguru

import eu.kanade.tachiyomi.animesource.model.AnimeFilter
import eu.kanade.tachiyomi.animesource.model.AnimeFilterList

fun getFilters() = AnimeFilterList(
    AnimeFilter.Header("Only One Filter Works at a time!!"),
    AnimeFilter.Header("Except tags, which can be combined!"),
    AnimeFilter.Header("Ignored With Text Search!!"),
    TagGroup(),
    CategoryFilter(),
    AnimeFilter.Separator(),
    ActressFilter(),
    ActorFilter(),
    StudioFilter(),
    MakerFilter(),
)

class UriPartFilter(val name: String, val urlPart: String)

abstract class UriPartFilters(name: String, private val tags: List<UriPartFilter>) : AnimeFilter.Select<String>(name, tags.map { it.name }.toTypedArray()) {
    fun toUrlPart() = tags[state].urlPart
}

class TagCheckBox(name: String, val urlPart: String) : AnimeFilter.CheckBox(name)

class TagGroup :
    AnimeFilter.Group<TagCheckBox>(
        "Tags",
        TAGS.filter { it.name.isNotEmpty() }.map { TagCheckBox(it.name, it.urlPart) },
    )

class CategoryFilter : UriPartFilters("Categories", CATEGORIES)

abstract class TextFilter(name: String, private val urlSubDirectory: String) : AnimeFilter.Text(name) {
    fun toUrlPart() = state.trim()
        .lowercase()
        .replace(SPECIAL_CHAR_REGEX, "-")
        .replace(TRAILING_HYPHEN_REGEX, "")
        .let { "/$urlSubDirectory/$it/" }

    companion object {
        private val SPECIAL_CHAR_REGEX = "[^a-z0-9]+".toRegex()
        private val TRAILING_HYPHEN_REGEX = "-+$".toRegex()
    }
}

class ActressFilter : TextFilter("Actress", "actress")

class ActorFilter : TextFilter("Actor", "actor")

class StudioFilter : TextFilter("Studio", "studio")

class MakerFilter : TextFilter("Maker", "maker")

fun <T> AnimeFilter<T>.toUrlPart(): String? = when (this) {
    is CategoryFilter -> this.toUrlPart()
    is ActressFilter -> this.toUrlPart()
    is ActorFilter -> this.toUrlPart()
    is StudioFilter -> this.toUrlPart()
    is MakerFilter -> this.toUrlPart()
    else -> null
}

val TAGS = listOf(
    UriPartFilter("", "/"),
    UriPartFilter("30 Years Old", "/tag/30-years-old/"),
    UriPartFilter("3D", "/tag/3d/"),
    UriPartFilter("3P", "/tag/3p/"),
    UriPartFilter("40 Years Old", "/tag/40-years-old/"),
    UriPartFilter("4HR", "/tag/4hr/"),
    UriPartFilter("69", "/tag/69/"),
    UriPartFilter("abuse", "/tag/abuse/"),
    UriPartFilter("Action", "/tag/action/"),
    UriPartFilter("Adopted Daughter", "/tag/adopted-daughter/"),
    UriPartFilter("Adultery", "/tag/adultery/"),
    UriPartFilter("Affair", "/tag/affair/"),
    UriPartFilter("AI-Generated Works", "/tag/ai-generated-works/"),
    UriPartFilter("Amateur", "/tag/amateur/"),
    UriPartFilter("Anal", "/tag/anal/"),
    UriPartFilter("anal penetration", "/tag/anal-penetration/"),
    UriPartFilter("Anchorwoman", "/tag/anchorwoman/"),
    UriPartFilter("Anime Characters", "/tag/anime-characters/"),
    UriPartFilter("aphrodisiac", "/tag/aphrodisiac/"),
    UriPartFilter("Around 40", "/tag/around-40/"),
    UriPartFilter("ASMR", "/tag/asmr/"),
    UriPartFilter("Ass", "/tag/ass/"),
    UriPartFilter("Athlete", "/tag/athlete/"),
    UriPartFilter("Aunt", "/tag/aunt/"),
    UriPartFilter("AV Actress", "/tag/av-actress/"),
    UriPartFilter("AV OPEN", "/tag/av-open/"),
    UriPartFilter("AV OPEN 2014 Middleweight", "/tag/av-open-2014-middleweight/"),
    UriPartFilter("AV Open 2016 Housewife & Mature Women Category", "/tag/av-open-2016-housewife-mature-women-category/"),
    UriPartFilter("AV OPEN 2016 MILF/Housewife Dept.", "/tag/av-open-2016-milf-housewife-dept/"),
    UriPartFilter("AV Open 2018 Maniac Fetish Category", "/tag/av-open-2018-maniac-fetish-category/"),
    UriPartFilter("Back", "/tag/back/"),
    UriPartFilter("Bareback", "/tag/bareback/"),
    UriPartFilter("Bath", "/tag/bath/"),
    UriPartFilter("Bathroom", "/tag/bathroom/"),
    UriPartFilter("BBW", "/tag/bbw/"),
    UriPartFilter("Beautiful Butt", "/tag/beautiful-butt/"),
    UriPartFilter("Beautiful Girl", "/tag/beautiful-girl/"),
    UriPartFilter("Beautiful legs", "/tag/beautiful-legs/"),
    UriPartFilter("Beautiful Pussy", "/tag/beautiful-pussy/"),
    UriPartFilter("Beautiful Skin", "/tag/beautiful-skin/"),
    UriPartFilter("Beauty Salon", "/tag/beauty-salon/"),
    UriPartFilter("Beauty Shop", "/tag/beauty-shop/"),
    UriPartFilter("Best of 2016", "/tag/best-of-2016/"),
    UriPartFilter("Best of 2017", "/tag/best-of-2017/"),
    UriPartFilter("Best of 2018", "/tag/best-of-2018/"),
    UriPartFilter("Best of 2019", "/tag/best-of-2019/"),
    UriPartFilter("Best of 2020", "/tag/best-of-2020/"),
    UriPartFilter("Best of 2021", "/tag/best-of-2021/"),
    UriPartFilter("Best of 2022", "/tag/best-of-2022/"),
    UriPartFilter("Best of 2023", "/tag/best-of-2023/"),
    UriPartFilter("Best of 2024", "/tag/best-of-2024/"),
    UriPartFilter("Best of 2025", "/tag/best-of-2025/"),
    UriPartFilter("Big ass", "/tag/big-ass/"),
    UriPartFilter("Big Butt", "/tag/big-butt/"),
    UriPartFilter("Big cock", "/tag/big-cock/"),
    UriPartFilter("Big tits", "/tag/big-tits/"),
    UriPartFilter("Bikini", "/tag/bikini/"),
    UriPartFilter("Bitch", "/tag/bitch/"),
    UriPartFilter("Black Actor", "/tag/black-actor/"),
    UriPartFilter("Blazer", "/tag/blazer/"),
    UriPartFilter("blog", "/tag/blog/"),
    UriPartFilter("Blonde", "/tag/blonde/"),
    UriPartFilter("Bloomers", "/tag/bloomers/"),
    UriPartFilter("Blow", "/tag/blow/"),
    UriPartFilter("Blowjob", "/tag/blowjob/"),
    UriPartFilter("Body Conscious", "/tag/body-conscious/"),
    UriPartFilter("Bodysuit", "/tag/bodysuit/"),
    UriPartFilter("Bondage", "/tag/bondage/"),
    UriPartFilter("Boobs fetish", "/tag/boobs/"),
    UriPartFilter("Booth Girl", "/tag/booth-girl/"),
    UriPartFilter("Breast Milk", "/tag/breast-milk/"),
    UriPartFilter("Breast Peeker", "/tag/breast-peeker/"),
    UriPartFilter("Bride", "/tag/bride/"),
    UriPartFilter("Bubble socks", "/tag/bubble-socks/"),
    UriPartFilter("Bukkake", "/tag/bukkake/"),
    UriPartFilter("Bunny Girl", "/tag/bunny-girl/"),
    UriPartFilter("Bus Guide", "/tag/bus-guide/"),
    UriPartFilter("Business Attire", "/tag/business-attire/"),
    UriPartFilter("Busty fetish", "/tag/busty-fetish/"),
    UriPartFilter("butt", "/tag/butt/"),
    UriPartFilter("C Student", "/tag/c-student/"),
    UriPartFilter("Candle", "/tag/candle/"),
    UriPartFilter("Car Sex", "/tag/car-sex/"),
    UriPartFilter("Catgirl", "/tag/catgirl/"),
    UriPartFilter("Celebrity", "/tag/celebrity/"),
    UriPartFilter("Censored", "/tag/censored/"),
    UriPartFilter("Cervix", "/tag/cervix/"),
    UriPartFilter("CFNM", "/tag/cfnm/"),
    UriPartFilter("Cheating", "/tag/cheating/"),
    UriPartFilter("Cheating Wife", "/tag/cheating-wife/"),
    UriPartFilter("Cheerleader", "/tag/cheerleader/"),
    UriPartFilter("Cheongsam", "/tag/cheongsam/"),
    UriPartFilter("Chubby", "/tag/chubby/"),
    UriPartFilter("Clit t*rture", "/tag/clit-trture/"),
    UriPartFilter("Close Up", "/tag/close-up/"),
    UriPartFilter("Clothed Sex", "/tag/clothed-sex/"),
    UriPartFilter("Club Activities / Manager", "/tag/club-activities-manager/"),
    UriPartFilter("Coarse hair", "/tag/coarse-hair/"),
    UriPartFilter("College student", "/tag/college-student/"),
    UriPartFilter("Companion", "/tag/companion/"),
    UriPartFilter("Conceived", "/tag/conceived/"),
    UriPartFilter("Confinement", "/tag/confinement/"),
    UriPartFilter("Cosplay", "/tag/cosplay/"),
    UriPartFilter("Couple", "/tag/couple/"),
    UriPartFilter("Cowgirl", "/tag/cowgirl/"),
    UriPartFilter("Cram school teacher", "/tag/cram-school-teacher/"),
    UriPartFilter("Creampie", "/tag/creampie/"),
    UriPartFilter("Cross Dressing", "/tag/cross-dressing/"),
    UriPartFilter("Crossdressing", "/tag/crossdressing/"),
    UriPartFilter("Cruel Expression", "/tag/cruel-expression/"),
    UriPartFilter("Cuckold", "/tag/cuckold/"),
    UriPartFilter("Cum", "/tag/cum/"),
    UriPartFilter("Cum between tits", "/tag/cum-between-tits/"),
    UriPartFilter("Cum Eating", "/tag/cum-eating/"),
    UriPartFilter("Cum in mouth", "/tag/cum-in-mouth/"),
    UriPartFilter("Cumshots", "/tag/cumshots/"),
    UriPartFilter("Cunnilingus", "/tag/cunnilingus/"),
    UriPartFilter("Cusco", "/tag/cusco/"),
    UriPartFilter("Cute", "/tag/cute/"),
    UriPartFilter("D cup", "/tag/d-cup/"),
    UriPartFilter("Dance", "/tag/dance/"),
    UriPartFilter("Dark System", "/tag/dark-system/"),
    UriPartFilter("Date", "/tag/date/"),
    UriPartFilter("Daughter", "/tag/daughter/"),
    UriPartFilter("Dead Drunk", "/tag/dead-drunk/"),
    UriPartFilter("Debuts", "/tag/debut-production/"),
    UriPartFilter("Deep Throat", "/tag/deep-throat/"),
    UriPartFilter("Deepthroat", "/tag/deepthroat/"),
    UriPartFilter("Delivery health", "/tag/delivery-health/"),
    UriPartFilter("Delivery table", "/tag/delivery-table/"),
    UriPartFilter("Delusion", "/tag/delusion/"),
    UriPartFilter("Delusion Tribe", "/tag/delusion-tribe/"),
    UriPartFilter("Digital Mosaic", "/tag/digital-mosaic/"),
    UriPartFilter("Dildo", "/tag/dildo/"),
    UriPartFilter("Dirty Talk", "/tag/dirty-talk/"),
    UriPartFilter("Dirty Words", "/tag/dirty-words/"),
    UriPartFilter("Documentary", "/tag/documentary/"),
    UriPartFilter("Doggy style", "/tag/doggy-style/"),
    UriPartFilter("Doll", "/tag/doll/"),
    UriPartFilter("Doujin", "/tag/original-collaboration/"),
    UriPartFilter("Drama", "/tag/drama/"),
    UriPartFilter("Drinking Party", "/tag/drinking-party/"),
    UriPartFilter("Drug", "/tag/drug/"),
    UriPartFilter("Early ejaculation", "/tag/early-ejaculation/"),
    UriPartFilter("eatpussy", "/tag/eatpussy/"),
    UriPartFilter("Edgeplay", "/tag/edgeplay/"),
    UriPartFilter("Egg Vibrator", "/tag/egg-vibrator/"),
    UriPartFilter("Elder Male", "/tag/elder-male/"),
    UriPartFilter("Electric Massager", "/tag/electric-massager/"),
    UriPartFilter("Enema", "/tag/enema/"),
    UriPartFilter("Entertainer", "/tag/entertainer/"),
    UriPartFilter("Erotic massage", "/tag/erotic-massage/"),
    UriPartFilter("Erotic Wear", "/tag/erotic-wear/"),
    UriPartFilter("Evil", "/tag/evil/"),
    UriPartFilter("Exclusive Distribution", "/tag/exclusive-distribution/"),
    UriPartFilter("Experience Confession", "/tag/experience-confession/"),
    UriPartFilter("Exposure", "/tag/exposure/"),
    UriPartFilter("Eyeness", "/tag/eyeness/"),
    UriPartFilter("F cup", "/tag/f-cup/"),
    UriPartFilter("Face Sitting", "/tag/face-sitting/"),
    UriPartFilter("Facesitting", "/tag/facesitting/"),
    UriPartFilter("Facial", "/tag/facial/"),
    UriPartFilter("Facials", "/tag/facials/"),
    UriPartFilter("Fair skin", "/tag/fair-skin/"),
    UriPartFilter("Fake Penis", "/tag/fake-penis/"),
    UriPartFilter("Falling for pleasure", "/tag/falling-for-pleasure/"),
    UriPartFilter("Fan Appreciation", "/tag/fan-appreciation/"),
    UriPartFilter("Fantasy", "/tag/fantasy/"),
    UriPartFilter("Fat", "/tag/fat/"),
    UriPartFilter("faux-skinned", "/tag/faux-skinned/"),
    UriPartFilter("Featured Actress", "/tag/featured-actress/"),
    UriPartFilter("Featured Creampie", "/tag/featured-creampie/"),
    UriPartFilter("Fellatio", "/tag/fellatio/"),
    UriPartFilter("Fellatio q", "/tag/fellatio-q/"),
    UriPartFilter("Female Boss", "/tag/female-boss/"),
    UriPartFilter("Female College Student", "/tag/female-college-student/"),
    UriPartFilter("Female Doctor", "/tag/female-doctor/"),
    UriPartFilter("Female Dominant", "/tag/female-dominant/"),
    UriPartFilter("Female investigator", "/tag/female-investigator/"),
    UriPartFilter("Female Ninja", "/tag/female-ninja/"),
    UriPartFilter("Female Streamer", "/tag/female-streamer/"),
    UriPartFilter("Female teacher", "/tag/female-teacher/"),
    UriPartFilter("Female Warrior", "/tag/female-warrior/"),
    UriPartFilter("Fetish", "/tag/fetish/"),
    UriPartFilter("Fetish Clan", "/tag/fetish-clan/"),
    UriPartFilter("Fighters", "/tag/fighters/"),
    UriPartFilter("Fighting Action", "/tag/fighting-action/"),
    UriPartFilter("Finger Fuck", "/tag/finger-fuck/"),
    UriPartFilter("Fingering", "/tag/fingering/"),
    UriPartFilter("First Person", "/tag/first-person/"),
    UriPartFilter("First Shoot", "/tag/first-shoot/"),
    UriPartFilter("First time", "/tag/first-time/"),
    UriPartFilter("Fisting", "/tag/fisting/"),
    UriPartFilter("Flexible", "/tag/flexible/"),
    UriPartFilter("Flirting", "/tag/flirting/"),
    UriPartFilter("Foot Fetish", "/tag/foot-fetish/"),
    UriPartFilter("Footjob", "/tag/footjob/"),
    UriPartFilter("For Women", "/tag/for-women/"),
    UriPartFilter("Foreign Objects", "/tag/foreign-objects/"),
    UriPartFilter("Full Service", "/tag/full-service/"),
    UriPartFilter("Futanari", "/tag/futanari/"),
    UriPartFilter("Gag · Comedy", "/tag/gag-%c2%b7-comedy/"),
    UriPartFilter("Gal", "/tag/gal/"),
    UriPartFilter("Gangbang", "/tag/gangbang/"),
    UriPartFilter("Gay", "/tag/gay/"),
    UriPartFilter("Girl Cosplay", "/tag/girl-cosplay/"),
    UriPartFilter("Girl Gacha", "/tag/girl-gacha/"),
    UriPartFilter("Glasses", "/tag/glasses/"),
    UriPartFilter("Gokkun", "/tag/gokkun/"),
    UriPartFilter("Gonzo", "/tag/gonzo/"),
    UriPartFilter("Granny", "/tag/granny/"),
    UriPartFilter("Gym Clothes", "/tag/gym-clothes/"),
    UriPartFilter("Gymnastics Uniform", "/tag/gymnastics-uniform/"),
    UriPartFilter("Handjob", "/tag/handjob/"),
    UriPartFilter("Hardcore", "/tag/hardcore/"),
    UriPartFilter("Harem", "/tag/harem/"),
    UriPartFilter("Have boyfriend", "/tag/have-boyfriend/"),
    UriPartFilter("High Definition", "/tag/high-definition/"),
    UriPartFilter("Historical Play", "/tag/historical-play/"),
    UriPartFilter("Home", "/tag/home/"),
    UriPartFilter("Horror", "/tag/horror/"),
    UriPartFilter("Hospital / Clinic", "/tag/hospital-clinic/"),
    UriPartFilter("Hostess", "/tag/hostess/"),
    UriPartFilter("Hostesses", "/tag/hostesses/"),
    UriPartFilter("Hot Girl", "/tag/hot-girl/"),
    UriPartFilter("Hot Spring", "/tag/hot-spring/"),
    UriPartFilter("Hotel", "/tag/hotel/"),
    UriPartFilter("Housewife", "/tag/housewife/"),
    UriPartFilter("How To", "/tag/how-to/"),
    UriPartFilter("Huge Butt", "/tag/huge-butt/"),
    UriPartFilter("huge cocks", "/tag/huge-cock/"),
    UriPartFilter("Huge Dick - Large Dick", "/tag/huge-dick-large-dick/"),
    UriPartFilter("Huge Tits", "/tag/huge-tits/"),
    UriPartFilter("Humiliation", "/tag/humiliation/"),
    UriPartFilter("Hyper-Girimoza", "/tag/hyper-girimoza/"),
    UriPartFilter("Hypnosis", "/tag/hypnosis/"),
    UriPartFilter("Idol", "/tag/idol/"),
    UriPartFilter("Idol & Celebrity", "/tag/idol-celebrity/"),
    UriPartFilter("Image video", "/tag/image-video/"),
    UriPartFilter("Immediate Oral", "/tag/immediate-oral/"),
    UriPartFilter("Impregnation", "/tag/impregnation/"),
    UriPartFilter("Impromptu Sex", "/tag/impromptu-sex/"),
    UriPartFilter("Improve premature ejaculation", "/tag/improve-premature-ejaculation/"),
    UriPartFilter("Inc*st", "/tag/incst/"),
    UriPartFilter("incest", "/tag/incest/"),
    UriPartFilter("Innocent", "/tag/innocent/"),
    UriPartFilter("Instructor", "/tag/instructor/"),
    UriPartFilter("Insult", "/tag/insult/"),
    UriPartFilter("Internet cafe", "/tag/internet-cafe/"),
    UriPartFilter("Interview", "/tag/interview/"),
    UriPartFilter("Intimate", "/tag/intimate/"),
    UriPartFilter("j", "/tag/j/"),
    UriPartFilter("Japanese Bondage", "/tag/japanese-bondage/"),
    UriPartFilter("JD", "/tag/jd/"),
    UriPartFilter("Kimono", "/tag/kimono/"),
    UriPartFilter("Kiss", "/tag/kiss/"),
    UriPartFilter("Kiss Kiss", "/tag/kiss-kiss/"),
    UriPartFilter("Kissing", "/tag/kissing/"),
    UriPartFilter("Knee Socks", "/tag/knee-socks/"),
    UriPartFilter("Lady", "/tag/lady/"),
    UriPartFilter("Landlady", "/tag/landlady/"),
    UriPartFilter("Leg Fetish", "/tag/leg-fetish/"),
    UriPartFilter("Leotard", "/tag/leotard/"),
    UriPartFilter("Lesbian", "/tag/lesbian/"),
    UriPartFilter("Lesbian Kiss", "/tag/lesbian-kiss/"),
    UriPartFilter("Lingerie", "/tag/lingerie/"),
    UriPartFilter("Long Boots", "/tag/long-boots/"),
    UriPartFilter("Look-alike", "/tag/look-alike/"),
    UriPartFilter("Loose Socks", "/tag/loose-socks/"),
    UriPartFilter("Lotion", "/tag/lotion/"),
    UriPartFilter("Lotion Oil", "/tag/lotion-oil/"),
    UriPartFilter("Love", "/tag/love/"),
    UriPartFilter("Lubricant", "/tag/lubricant/"),
    UriPartFilter("M-girl", "/tag/m-girl/"),
    UriPartFilter("M-man", "/tag/m-man/"),
    UriPartFilter("Magic Gal", "/tag/magic-gal/"),
    UriPartFilter("Maid", "/tag/maid/"),
    UriPartFilter("Male Squirting", "/tag/male-squirting/"),
    UriPartFilter("Man Squirting", "/tag/man-squirting/"),
    UriPartFilter("Married", "/tag/married/"),
    UriPartFilter("Married Woman", "/tag/married-woman/"),
    UriPartFilter("Masked", "/tag/masked/"),
    UriPartFilter("Masochist", "/tag/masochist/"),
    UriPartFilter("Massage", "/tag/massage/"),
    UriPartFilter("Masturbation", "/tag/masturbation/"),
    UriPartFilter("Masturbation Support", "/tag/masturbation-support/"),
    UriPartFilter("Masturbator", "/tag/masturbator/"),
    UriPartFilter("Mature", "/tag/mature/"),
    UriPartFilter("Mature Woman", "/tag/mature-woman/"),
    UriPartFilter("MILF", "/tag/milf/"),
    UriPartFilter("Mini", "/tag/mini/"),
    UriPartFilter("Mini Skirt", "/tag/mini-skirt/"),
    UriPartFilter("Miniskirt", "/tag/miniskirt/"),
    UriPartFilter("Misfire", "/tag/misfire/"),
    UriPartFilter("Miss", "/tag/miss/"),
    UriPartFilter("Missionary", "/tag/missionary/"),
    UriPartFilter("Mistress", "/tag/mistress/"),
    UriPartFilter("Model", "/tag/model/"),
    UriPartFilter("Molester", "/tag/molester/"),
    UriPartFilter("Mom Friends", "/tag/mom-friends/"),
    UriPartFilter("Mom on top", "/tag/mom-on-top/"),
    UriPartFilter("Mother", "/tag/mother/"),
    UriPartFilter("Mourning", "/tag/mourning/"),
    UriPartFilter("Multiple Story", "/tag/multiple-story/"),
    UriPartFilter("Muscle", "/tag/muscle/"),
    UriPartFilter("Naked Apron", "/tag/naked-apron/"),
    UriPartFilter("Nampa", "/tag/nampa/"),
    UriPartFilter("Nasty", "/tag/nasty/"),
    UriPartFilter("Neglect", "/tag/neglect/"),
    UriPartFilter("Netori", "/tag/netori/"),
    UriPartFilter("Nice Tits", "/tag/nice-tits/"),
    UriPartFilter("Nipples", "/tag/nipples/"),
    UriPartFilter("No", "/tag/no/"),
    UriPartFilter("No Bra", "/tag/no-bra/"),
    UriPartFilter("No mosaic", "/tag/no-mosaic/"),
    UriPartFilter("No moss", "/tag/no-moss/"),
    UriPartFilter("No Undies", "/tag/no-undies/"),
    UriPartFilter("Nose Hook", "/tag/nose-hook/"),
    UriPartFilter("NTR", "/tag/ntr/"),
    UriPartFilter("Nude", "/tag/nude/"),
    UriPartFilter("Nude Apron", "/tag/nude-apron/"),
    UriPartFilter("Nun", "/tag/nun/"),
    UriPartFilter("Nurse", "/tag/nurse/"),
    UriPartFilter("Oil", "/tag/oil/"),
    UriPartFilter("Oil massage", "/tag/oil-massage/"),
    UriPartFilter("OL", "/tag/ol/"),
    UriPartFilter("Old Friend", "/tag/childhood-friend/"),
    UriPartFilter("Older sister", "/tag/older-sister/"),
    UriPartFilter("Older Woman", "/tag/older-woman/"),
    UriPartFilter("Omnibus", "/tag/omnibus/"),
    UriPartFilter("Onahole", "/tag/onahole/"),
    UriPartFilter("Only a few left", "/tag/only-a-few-left/"),
    UriPartFilter("Orgasm", "/tag/orgasm/"),
    UriPartFilter("Orgy", "/tag/orgy/"),
    UriPartFilter("Original", "/tag/original/"),
    UriPartFilter("Original one-shot uncut individual shooting", "/tag/original-one-shot-uncut-individual-shooting/"),
    UriPartFilter("Otaku", "/tag/otaku/"),
    UriPartFilter("Other", "/tag/other/"),
    UriPartFilter("Other Asian", "/tag/other-asian/"),
    UriPartFilter("Other fetish", "/tag/other-fetish/"),
    UriPartFilter("Other Fetishes", "/tag/other-fetishes/"),
    UriPartFilter("Other Students", "/tag/other-students/"),
    UriPartFilter("Others", "/tag/others/"),
    UriPartFilter("Outdoor", "/tag/outdoor/"),
    UriPartFilter("Outdoors", "/tag/outdoors/"),
    UriPartFilter("Over 16 Hours", "/tag/over-16-hours/"),
    UriPartFilter("Oversea Import", "/tag/oversea-import/"),
    UriPartFilter("Paipan", "/tag/paipan/"),
    UriPartFilter("Pajama", "/tag/pajama/"),
    UriPartFilter("Panty flash", "/tag/panty-flash/"),
    UriPartFilter("Panty Shot", "/tag/panty-shot/"),
    UriPartFilter("Panty Voyeur", "/tag/panty-voyeur/"),
    UriPartFilter("Pantyhose", "/tag/pantyhose/"),
    UriPartFilter("Pantyhose/Tights", "/tag/pantyhose-tights/"),
    UriPartFilter("Penis caretaker", "/tag/penis-caretaker/"),
    UriPartFilter("Personal shooting", "/tag/personal-shooting/"),
    UriPartFilter("Pervert", "/tag/pervert/"),
    UriPartFilter("Pet walk", "/tag/pet-walk/"),
    UriPartFilter("Petite", "/tag/petite/"),
    UriPartFilter("Photo taken with smartphone", "/tag/photo-taken-with-smartphone/"),
    UriPartFilter("Physical Education", "/tag/physical-education/"),
    UriPartFilter("Pick Up", "/tag/pick-up/"),
    UriPartFilter("Picking Up Girls", "/tag/picking-up-girls/"),
    UriPartFilter("Pickup", "/tag/pickup/"),
    UriPartFilter("Piss Drinking", "/tag/piss-drinking/"),
    UriPartFilter("planning", "/tag/planning/"),
    UriPartFilter("Plump", "/tag/plump/"),
    UriPartFilter("plural", "/tag/plural/"),
    UriPartFilter("Ponytail", "/tag/ponytail/"),
    UriPartFilter("Pornography", "/tag/pornography/"),
    UriPartFilter("POV", "/tag/pov/"),
    UriPartFilter("Prank", "/tag/prank/"),
    UriPartFilter("Pregnancy", "/tag/pregnancy/"),
    UriPartFilter("Pregnant", "/tag/pregnant/"),
    UriPartFilter("Pregnant Woman", "/tag/pregnant-woman/"),
    UriPartFilter("Premature Ejaculation", "/tag/premature-ejaculation/"),
    UriPartFilter("Priestess", "/tag/priestess/"),
    UriPartFilter("Princess", "/tag/princess/"),
    UriPartFilter("Promiscuity", "/tag/promiscuity/"),
    UriPartFilter("Prostitutes", "/tag/prostitutes/"),
    UriPartFilter("PtM", "/tag/ptm/"),
    UriPartFilter("Pubic hair", "/tag/pubic-hair/"),
    UriPartFilter("Pure", "/tag/pure/"),
    UriPartFilter("Pussy", "/tag/pussy/"),
    UriPartFilter("Race Queen", "/tag/race-queen/"),
    UriPartFilter("Rape", "/tag/rape/"),
    UriPartFilter("Rare", "/tag/rare/"),
    UriPartFilter("Raw", "/tag/raw/"),
    UriPartFilter("Raw change of clothes", "/tag/raw-change-of-clothes/"),
    UriPartFilter("Raw sex", "/tag/raw-sex/"),
    UriPartFilter("Rayya", "/tag/rayya/"),
    UriPartFilter("Real", "/tag/real/"),
    UriPartFilter("Receptionist", "/tag/receptionist/"),
    UriPartFilter("Reprinted Edition", "/tag/reprinted-edition/"),
    UriPartFilter("Resale", "/tag/resale/"),
    UriPartFilter("Reserved Role", "/tag/reserved-role/"),
    UriPartFilter("Restraint", "/tag/restraint/"),
    UriPartFilter("Restraints", "/tag/restraints/"),
    UriPartFilter("Reversed Role", "/tag/reversed-role/"),
    UriPartFilter("Risky Mosaic", "/tag/risky-mosaic/"),
    UriPartFilter("Rolling Back Eyes / Fainting", "/tag/rolling-back-eyes-fainting/"),
    UriPartFilter("Romance", "/tag/romance/"),
    UriPartFilter("Round girl", "/tag/round-girl/"),
    UriPartFilter("Sailor suit", "/tag/sailor-suit/"),
    UriPartFilter("Sailor Uniform", "/tag/sailor-uniform/"),
    UriPartFilter("Same-Sex Kissing", "/tag/same-sex-kissing/"),
    UriPartFilter("School", "/tag/school/"),
    UriPartFilter("School stuff", "/tag/school-stuff/"),
    UriPartFilter("School Swimsuit", "/tag/school-swimsuit/"),
    UriPartFilter("School Uniform", "/tag/school-uniform/"),
    UriPartFilter("School-themed", "/tag/school-themed/"),
    UriPartFilter("Schoolgirl", "/tag/schoolgirl/"),
    UriPartFilter("schoolgirls", "/tag/schoolgirls/"),
    UriPartFilter("Schoolgirls Fapping to attires and school issues.", "/tag/school-girls/"),
    UriPartFilter("Secretary", "/tag/secretary/"),
    UriPartFilter("Semen", "/tag/semen/"),
    UriPartFilter("Sensitive", "/tag/sensitive/"),
    UriPartFilter("serious", "/tag/serious/"),
    UriPartFilter("Serious cosplay", "/tag/serious-cosplay/"),
    UriPartFilter("Sex Conversion / Feminized", "/tag/sex-conversion-feminized/"),
    UriPartFilter("Sex Toys", "/tag/sex-toys/"),
    UriPartFilter("Sexy", "/tag/sexy/"),
    UriPartFilter("Sexy lingerie", "/tag/sexy-lingerie/"),
    UriPartFilter("SF", "/tag/sf/"),
    UriPartFilter("Shame", "/tag/shame/"),
    UriPartFilter("Shaved", "/tag/shaved/"),
    UriPartFilter("Shaved Pussy", "/tag/shaved-pussy/"),
    UriPartFilter("Shemale", "/tag/shemale/"),
    UriPartFilter("Shibari", "/tag/shibari/"),
    UriPartFilter("Shotacon", "/tag/shotacon/"),
    UriPartFilter("Shower", "/tag/shower/"),
    UriPartFilter("Showgirl", "/tag/showgirl/"),
    UriPartFilter("Sister", "/tag/sister/"),
    UriPartFilter("Slave", "/tag/slave/"),
    UriPartFilter("Slender", "/tag/slender/"),
    UriPartFilter("Slut", "/tag/slut/"),
    UriPartFilter("Slutty", "/tag/slutty/"),
    UriPartFilter("SM", "/tag/sm/"),
    UriPartFilter("Small boobs", "/tag/small-boobs/"),
    UriPartFilter("Small tits", "/tag/tits/"),
    UriPartFilter("Soapland", "/tag/soapland/"),
    UriPartFilter("Sold out", "/tag/sold-out/"),
    UriPartFilter("Solowork", "/tag/solowork/"),
    UriPartFilter("Spanking", "/tag/spanking/"),
    UriPartFilter("Special Effects", "/tag/special-effects/"),
    UriPartFilter("Speculum", "/tag/speculum/"),
    UriPartFilter("Sport", "/tag/sport/"),
    UriPartFilter("Squirting", "/tag/squirting/"),
    UriPartFilter("Stepmother", "/tag/stepmother/"),
    UriPartFilter("Stewardess", "/tag/stewardess/"),
    UriPartFilter("Submissive Men", "/tag/submissive-men/"),
    UriPartFilter("Submissive Woman", "/tag/submissive-woman/"),
    UriPartFilter("Subordinates / Colleagues", "/tag/subordinates-colleagues/"),
    UriPartFilter("Suit", "/tag/suit/"),
    UriPartFilter("Sun tan", "/tag/sun-tan/"),
    UriPartFilter("Super Short Skirt", "/tag/super-short-skirt/"),
    UriPartFilter("Swallowing", "/tag/swallowing/"),
    UriPartFilter("Sweat", "/tag/sweat/"),
    UriPartFilter("Swimsuit", "/tag/swimsuit/"),
    UriPartFilter("Swingers", "/tag/swingers/"),
    UriPartFilter("T*rture", "/tag/trture/"),
    UriPartFilter("tag：", "/tag/tag%ef%bc%9a/"),
    UriPartFilter("tag：Creampie", "/tag/tag%ef%bc%9acreampie/"),
    UriPartFilter("Taiwan", "/tag/taiwan/"),
    UriPartFilter("Taiwan Model", "/tag/taiwan-model/"),
    UriPartFilter("Tall", "/tag/tall/"),
    UriPartFilter("Tanned Beauty", "/tag/tanned-beauty/"),
    UriPartFilter("Teacher", "/tag/teacher/"),
    UriPartFilter("Teen", "/tag/girl/"),
    UriPartFilter("Tentacle", "/tag/tentacle/"),
    UriPartFilter("Therapist", "/tag/therapist/"),
    UriPartFilter("Threesome / Foursome", "/tag/threesome-foursome/"),
    UriPartFilter("Tickling", "/tag/tickling/"),
    UriPartFilter("Time Stop", "/tag/time-stop/"),
    UriPartFilter("Tit fuck", "/tag/tit-fuck/"),
    UriPartFilter("Titty fuck", "/tag/titty-fuck/"),
    UriPartFilter("Toy", "/tag/toy/"),
    UriPartFilter("Toy t*rture", "/tag/toy-trture/"),
    UriPartFilter("Toys", "/tag/toys/"),
    UriPartFilter("Training", "/tag/training/"),
    UriPartFilter("Transformed Heroine", "/tag/transformed-heroine/"),
    UriPartFilter("Transsexual", "/tag/transsexual/"),
    UriPartFilter("Travel", "/tag/travel/"),
    UriPartFilter("Tsundere", "/tag/tsundere/"),
    UriPartFilter("Tutor", "/tag/tutor/"),
    UriPartFilter("uncensored", "/tag/uncensored/"),
    UriPartFilter("Underwear", "/tag/underwear/"),
    UriPartFilter("Uniform", "/tag/uniform/"),
    UriPartFilter("Unshaved", "/tag/unshaved/"),
    UriPartFilter("Urination", "/tag/urination/"),
    UriPartFilter("US/EU Porn", "/tag/us-eu-porn/"),
    UriPartFilter("User Submission", "/tag/user-submission/"),
    UriPartFilter("Vacuum", "/tag/vacuum/"),
    UriPartFilter("Variety", "/tag/variety/"),
    UriPartFilter("Various Professions", "/tag/various-professions/"),
    UriPartFilter("Vibe", "/tag/vibe/"),
    UriPartFilter("Vibrator", "/tag/vibrator/"),
    UriPartFilter("virgin", "/tag/virgin/"),
    UriPartFilter("virgin man", "/tag/virgin-man/"),
    UriPartFilter("Virginity", "/tag/virginity/"),
    UriPartFilter("Voluptuous", "/tag/voluptuous/"),
    UriPartFilter("Vomit", "/tag/vomit/"),
    UriPartFilter("Voyeur", "/tag/voyeur/"),
    UriPartFilter("Voyeurism", "/tag/voyeurism/"),
    UriPartFilter("VR", "/tag/vr/"),
    UriPartFilter("Vtuber", "/tag/vtuber/"),
    UriPartFilter("Waist", "/tag/waist/"),
    UriPartFilter("Waitress", "/tag/waitress/"),
    UriPartFilter("While stocks last", "/tag/while-stocks-last/"),
    UriPartFilter("White Actress", "/tag/white-actress/"),
    UriPartFilter("Widow", "/tag/widow/"),
    UriPartFilter("Wife", "/tag/wife/"),
    UriPartFilter("Works Over Four Hours", "/tag/works-over-four-hours/"),
    UriPartFilter("Yoga", "/tag/yoga/"),
    UriPartFilter("Young", "/tag/young/"),
    UriPartFilter("Young Lady", "/tag/young-lady/"),
    UriPartFilter("Young wife", "/tag/young-wife/"),
    UriPartFilter("Yukata", "/tag/yukata/"),
)

val CATEGORIES = listOf(
    UriPartFilter("", "/"),
    UriPartFilter("1080p", "/category/1080p/"),
    UriPartFilter("4K", "/category/4k/"),
    UriPartFilter("Amateur", "/category/amateur/"),
    UriPartFilter("Blog", "/category/blog/"),
    UriPartFilter("Decensored", "/category/decensored/"),
    UriPartFilter("English subbed JAV", "/category/english-subbed/"),
    UriPartFilter("FC2", "/category/fc2/"),
    UriPartFilter("HD", "/category/hd/"),
    UriPartFilter("Idol", "/category/idol/"),
    UriPartFilter("JAV", "/category/jav/"),
    UriPartFilter("LEGACY", "/category/legacy/"),
    UriPartFilter("UNCENSORED", "/category/jav-uncensored/"),
    UriPartFilter("VR AV", "/category/vr-av/"),
)
