package eu.kanade.tachiyomi.animeextension.all.animeonsen

import eu.kanade.tachiyomi.animesource.model.AnimeFilter
import eu.kanade.tachiyomi.animesource.model.AnimeFilterList

object AnimeOnsenFilters {
    class GenreFilter : AnimeFilter.Select<String>("Genre", GENRE_ENTRIES.toTypedArray(), 0) {
        fun getValue() = if (state == 0) null else GENRE_VALUES[state]

        companion object {
            private val GENRE_ENTRIES = listOf(
                "All",
                "Action",
                "Adult Cast",
                "Adventure",
                "Anthropomorphic",
                "Avant Garde",
                "Award Winning",
                "Childcare",
                "Combat Sports",
                "Comedy",
                "Crossdressing",
                "Cute Girls Doing Cute Things",
                "Delinquents",
                "Detective",
                "Drama",
                "Ecchi",
                "Educational",
                "Fantasy",
                "Gag Humor",
                "Gore",
                "Gourmet",
                "Harem",
                "High Stakes Game",
                "Historical",
                "Horror",
                "Idols (Female)",
                "Idols (Male)",
                "Isekai",
                "Iyashikei",
                "Love Polygon",
                "Josei",
                "Kids",
                "Magical Sex Shift",
                "Mahou Shoujo",
                "Martial Arts",
                "Mecha",
                "Medical",
                "Military",
                "Music",
                "Mystery",
                "Mythology",
                "Organized Crime",
                "Otaku Culture",
                "Parody",
                "Performing Arts",
                "Pets",
                "Psychological",
                "Racing",
                "Reincarnation",
                "Reverse Harem",
                "Romance",
                "Romantic Subtext",
                "Samurai",
                "School",
                "Sci-Fi",
                "Seinen",
                "Shoujo",
                "Shoujo Ai",
                "Shounen",
                "Shounen Ai",
                "Showbiz",
                "Slice of Life",
                "Space", "Sports",
                "Strategy Game",
                "Super Power",
                "Supernatural",
                "Survival",
                "Team Sports",
                "Suspense",
                "Time Travel",
                "Vampire",
                "Video Game",
                "Visual Arts",
                "Workplace",
            )
            private val GENRE_VALUES = listOf(
                "",
                "action",
                "adult-cast",
                "adventure",
                "anthropomorphic",
                "avant-garde",
                "award-winning",
                "childcare",
                "combat-sports",
                "comedy",
                "crossdressing",
                "cgdct",
                "delinquents",
                "detective",
                "drama",
                "ecchi",
                "educational",
                "fantasy",
                "gag-humor",
                "gore",
                "gourmet",
                "harem",
                "high-stakes-game",
                "historical",
                "horror",
                "idols-female",
                "idols-male",
                "isekai",
                "iyashikei",
                "love-polygon",
                "josei",
                "kids",
                "magical-sex-shift",
                "mahou-shoujo",
                "martial-arts",
                "mecha",
                "medical",
                "military",
                "music",
                "mystery",
                "mythology",
                "organized-crime",
                "otaku-culture",
                "parody",
                "performing-arts",
                "pets",
                "psychological",
                "racing",
                "reincarnation",
                "reverse-harem",
                "romance",
                "romantic-subtext",
                "samurai",
                "school",
                "sci-fi",
                "seinen",
                "shoujo",
                "shoujo-ai",
                "shounen",
                "shounen-ai",
                "showbiz",
                "slice-of-life",
                "space",
                "sports",
                "strategy-game",
                "super-power",
                "supernatural",
                "survival",
                "team-sports",
                "suspense",
                "time-travel",
                "vampire",
                "video-game",
                "visual-arts",
                "workplace",
            )
        }
    }

    val FILTER_LIST get() = AnimeFilterList(
        GenreFilter(),
    )
}
